import "./ditto.css";
import MediaCard from "./components/media-card";
// Generated by clone-site. Do not edit by hand.
const MediaCard_data = [
    { alt: "Dedicated Account Manager", imgSrc: "/assets/cloned/images/4f10cec84dfd.png", text: "01", title: "Dedicated Account Manager", description: "One point of contact across all your projects. We hold your specs and your preferences - so you're not rebuilding context every call." },
    { alt: "Your Partner in Design", imgSrc: "/assets/cloned/images/56edf4ccbfc1.png", text: "02", title: "Your Partner in Design", description: "COM yardage calculations, full custom workroom capabilities and configurations only offered to the trade." },
    { alt: "Exceptional Experience", imgSrc: "/assets/cloned/images/8d6f0ce966a1.jpg", text: "03", title: "Exceptional Experience", description: "Priority scheduling in production. Quotes within two business days." }
];
const MediaCard_meta: string[][] = [
    ["n61", "style-div-3", "n63", "style-div-4", "n65", "style-shopify-section-template-20207706308770-tabs", "n67", "style-div-5"],
    ["n69", "style-div-6", "n71", "n72", "n73", "n74", "style-p", "n76"],
    ["style-div-7", "n78", "style-div-8", "n80", "style-shades-guide-top", "n82", "n83", "n84"]
];

export default function Page() {
  return (
    <>
      <section className="grid relative grid-cols-[minmax(20px,1fr)_minmax(0,1400px)_minmax(20px,1fr)] max-md:grid-cols-[16px_343px_16px] md:max-lg:grid-cols-[16px_736px_16px]" data-ditto-id="style-shopify-section-template-20207705292962-main" aria-hidden="true" id="shopify-section-template--20207706079394__hero">
        <section className="min-h-184 flex relative isolate items-end col-span-full overflow-hidden text-background max-md:min-h-[43.1375rem] md:max-lg:min-h-[54.4rem]" style={{ backgroundImage: "linear-gradient(var(--clr-1) 0%, var(--clr-2) 100%)" }}>
          <img className="w-full h-full block absolute top-0 left-0 -z-2 min-w-0 max-w-full overflow-clip object-cover aspect-[auto_2400/1600]" data-component="image" alt="Design Services for Trade" height="1600" src="/assets/cloned/images/fc3269ce118b.webp" width="2400" />
          {" "}
          <div className="h-full block absolute top-0 inset-x-0 -z-1 min-w-0" style={{ backgroundImage: "linear-gradient(to top, var(--clr-3), var(--clr-4) 60%, var(--clr-4) 100%)" }} />
          <div className="block relative z-1 max-w-168 p-12 max-lg:py-8 max-lg:px-4">
            <h1 className="block mb-2 [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-[4rem] font-light italic leading-[4.1875rem] tracking-[-0.64px] [overflow-wrap:break-word] max-md:text-[2.5rem] max-md:leading-10.5 max-md:tracking-[-0.4px] md:max-lg:text-[2.875rem] md:max-lg:leading-[3rem] md:max-lg:tracking-[-0.46px]" data-component="heading">
              Design Services for Trade
            </h1>
            <p className="w-full max-w-128 block mb-5 text-color-018 text-sm font-light leading-[1.375rem] [overflow-wrap:break-word]">
              Project support from a dedicated team - built for the way you work.
            </p>
            <div className="flex flex-wrap gap-2">
              <a className="border border-solid border-color-002 block py-3.5 px-7 text-xs font-medium leading-[1.1875rem] tracking-[1.44px] uppercase bg-color-002 cursor-pointer" data-component="link" href="https://form.typeform.com/to/HtgnBwcl">
                {"\n          Book a project review\n        "}
              </a>
              <a className="border border-solid border-surface block py-3.5 px-7 text-xs font-medium leading-[1.1875rem] tracking-[1.44px] uppercase cursor-pointer" data-component="link" href="/pages/trade">
                {"\n          Apply for trade\n        "}
              </a>
            </div>
            {" "}
          </div>
          {" "}
        </section>
        {" "}
      </section>
      <section className="grid relative grid-cols-[minmax(20px,1fr)_minmax(0,1400px)_minmax(20px,1fr)] max-md:grid-cols-[16px_343px_16px] md:max-lg:grid-cols-[16px_736px_16px]" aria-hidden="true" id="shopify-section-template--20207706079394__intro">
        <section className="block py-11 col-span-full bg-accent max-lg:py-8">
          <div className="h-full grid max-w-350 px-8 items-center gap-16 grid-cols-2 max-md:px-4 max-lg:items-start max-md:gap-8 max-md:grid-cols-1 md:max-lg:px-6 md:max-lg:gap-5" data-ditto-id="style-link-6">
            <div className="block overflow-hidden bg-accent aspect-[0.8] max-md:max-h-[30.45rem] max-md:aspect-[4/3] md:max-lg:aspect-[3/4]" data-ditto-id="style-link-7">
              <img className="w-full h-180 block max-w-full overflow-clip object-cover aspect-[auto_1400/1750] max-md:h-64 md:max-lg:h-117" data-component="image" alt="An extension of your workflow." height="1750" src="/assets/cloned/images/d42380bd1dc3.jpg" width="1400" />
            </div>
            {" "}
            <div className="flex max-w-[26.64rem] flex-col gap-5 max-lg:max-w-none">
              <p className="block text-color-002 text-xs font-medium leading-[1.1875rem] tracking-[2.16px] uppercase [overflow-wrap:break-word]">
                Window Treatement Expertise
              </p>
              <h2 className="block [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-5xl font-light italic leading-[3.125rem] tracking-[-0.48px] [overflow-wrap:break-word] max-lg:text-[2rem] max-lg:leading-[2.125rem] max-lg:tracking-[-0.32px]" data-component="heading">
                An extension of your workflow.
              </h2>
              <div className="block font-light leading-[1.625rem]">
                <p className="block [overflow-wrap:break-word]">
                  We are a partner on your projects, matching your pace and handling the complexities of custom window treatments to bring your vision to life.
                </p>
              </div>
              <a className="border-b border-solid border-b-foreground block mt-2 pb-1 self-start text-xs font-medium leading-[1.1875rem] tracking-[2.16px] uppercase cursor-pointer" data-ditto-id="style-button" data-component="link" href="https://form.typeform.com/to/HtgnBwcl">
                {"\n          Book a call\n          "}
                <span className="inline-block ml-1.5" data-ditto-id="style-button-2" aria-hidden="true">
                  →
                </span>
                {" "}
              </a>
            </div>
            {" "}
          </div>
          {" "}
        </section>
        {" "}
      </section>
      <section className="grid relative grid-cols-[minmax(20px,1fr)_minmax(0,1400px)_minmax(20px,1fr)] grid-rows-1 aspect-[1.418] max-md:grid-cols-[16px_343px_16px] max-md:aspect-[0.26] md:max-lg:grid-cols-[16px_736px_16px] md:max-lg:aspect-[0.353]" aria-hidden="true" id="shopify-section-template--20207706079394__principles">
        <section className="block py-11 col-span-full bg-accent max-lg:py-8">
          <div className="h-full block max-w-350 px-8 max-md:px-4 md:max-lg:px-6">
            <div className="flex max-w-176 mb-16 mx-auto flex-col gap-4 text-center max-lg:mb-10">
              <h2 className="block [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-[2.8125rem] leading-[3.0625rem] tracking-[-0.22px] [overflow-wrap:break-word] max-lg:text-3xl max-lg:leading-[2.0625rem] max-lg:tracking-[-0.15px]" data-component="heading">
                How we work with trade
              </h2>
              <p className="block max-w-152 mx-auto text-color-011 font-light leading-[1.625rem] [overflow-wrap:break-word]">
                We believe good design is the foundation of a good home. Here's what goes into every window treatment we make.
              </p>
            </div>
            <div className="grid gap-[3.2rem] grid-cols-3 max-lg:gap-12 max-lg:grid-cols-1" data-ditto-id="style-div-2">
              {MediaCard_data.map((d, i) => <MediaCard key={i} d={d} />)}
            </div>
          </div>
          {" "}
        </section>
        {" "}
      </section>
      <section className="grid relative grid-cols-[minmax(20px,1fr)_minmax(0,1400px)_minmax(20px,1fr)] grid-rows-1 aspect-[4.285] max-md:grid-cols-[16px_343px_16px] max-md:aspect-[1.109] md:max-lg:grid-cols-[16px_736px_16px] md:max-lg:aspect-[3.039]" aria-hidden="true" id="shopify-section-template--20207706079394__final-cta">
        <div className="block py-11 col-start-2 bg-background max-lg:py-8" data-ditto-id="style-link-8">
          <div className="h-full flex max-w-208 mx-auto px-8 flex-col items-center gap-4 text-center max-md:px-4 md:max-lg:px-6">
            <p className="block text-color-002 text-xs font-medium leading-[1.1875rem] tracking-[2.16px] uppercase [overflow-wrap:break-word]" data-ditto-id="style-link-9">
              Already a trade member?
            </p>
            <h1 className="block max-w-full [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-[3.5rem] font-light italic leading-[3.5625rem] tracking-[-0.56px] [overflow-wrap:break-word] max-lg:text-4xl max-lg:leading-[2.3125rem] max-lg:tracking-[-0.36px]" data-component="heading">
              Start your project today.
            </h1>
            <div className="block max-w-full text-color-003">
              <p className="block [overflow-wrap:break-word]">
                Not yet a member? Apply first - approval typically takes one to two business days.
              </p>
            </div>
            <div className="w-[46%] flex mt-2 flex-wrap gap-2 max-md:w-full max-md:flex-col md:max-lg:w-[51%]">
              <a className="h-[52.5938px] border border-solid border-foreground flex py-4 px-8 justify-center items-center text-background text-xs font-medium leading-[1.1875rem] tracking-[1.44px] uppercase bg-foreground cursor-pointer" data-ditto-id="style-link-10" data-component="button" href="https://form.typeform.com/to/HtgnBwcl">
                {"\n          Book a call\n        "}
              </a>
              <a className="h-[52.5938px] border border-solid border-foreground flex py-4 px-8 justify-center items-center text-xs font-medium leading-[1.1875rem] tracking-[1.44px] uppercase cursor-pointer" data-component="button" href="/pages/trade">
                {"\n          Apply for trade\n        "}
              </a>
            </div>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
    </>
  );
}
