import "./ditto.css";
// Generated by clone-site. Do not edit by hand.
export default function Page() {
  return (
    <>
      <div className="h-200 block relative z-50 overflow-hidden [animation-name:fadeIn] [animation-duration:0.4s] [animation-timing-function:ease-in-out] [animation-delay:0.8s] [animation-fill-mode:forwards] max-md:h-203 md:max-lg:h-256 2xl:h-270" id="root">
        <div className="h-full block">
          <div className="contents">
            <div className="block">
              <div className="h-0 block absolute inset-x-0 z-500" />
              <div className="h-full flex flex-col" data-ditto-id="style-dismiss-announcement">
                <div className="h-full flex relative flex-col items-center grow basis-0 [font-family:system-ui,_-apple-system,_'system-ui',_'Segoe_UI',_Roboto,_Oxygen,_Ubuntu,_Cantarell,_'Fira_Sans',_'Droid_Sans',_'Helvetica_Neue',_sans-serif] bg-color-022">
                  <header className="h-0 flex fixed inset-x-0 z-50 min-w-0 flex-col pointer-events-none" />
                  <main className="w-full flex flex-col">
                    <div className="h-200 flex absolute inset-x-0 min-w-0 max-md:h-203 md:max-lg:h-256 2xl:h-270">
                      <div className="w-full h-[clamp(768px,_100vh,_1440px)] grid relative z-1 items-center [grid-template-areas:'content'] overflow-auto grid-cols-1 grid-rows-1">
                        <div className="w-0 h-px flex absolute top-8 min-w-0" />
                        <fieldset className="w-full max-w-220 flex min-w-0 pt-6 pb-14 px-20 flex-col self-center [justify-self:center] gap-8 [grid-column-start:content] [grid-column-end:content] [grid-row-start:content] [grid-row-end:content] max-md:pb-35 max-md:px-8" aria-describedby="welcome-screen-description" aria-labelledby="welcome-screen-prefix welcome-screen-title" id="welcome-screen">
                          <div className="w-0 h-px flex absolute top-0 min-w-0 pointer-events-none" data-ditto-id="style-everhem-home" />
                          <div className="w-0 h-px flex absolute bottom-0 min-w-0 pointer-events-none" />
                          <div className="flex min-w-0 flex-col items-center grow gap-2 [filter:blur(0px)]">
                            <div className="flex min-w-0 items-start grow [filter:blur(0px)] max-md:flex-col max-md:items-center max-md:gap-2" data-ditto-id="style-link">
                              <h1 className="block rounded-sm items-center text-[2rem] leading-10 tracking-[-0.75px] text-center [word-break:break-word] max-md:text-[1.625rem] max-md:leading-8.5 max-md:tracking-[-0.5px]" data-component="heading" id="welcome-screen-title">
                                <span className="inline" data-ditto-id="style-link-2">
                                  Let’s create something beautiful.
                                </span>
                              </h1>
                            </div>
                            <div className="flex [filter:blur(0px)]">
                              <div className="block rounded-sm items-center text-color-023 text-lg leading-6 text-center [word-break:break-word] max-md:text-base max-md:leading-5.5" id="welcome-screen-description">
                                <span className="inline" data-ditto-id="style-link-3">
                                  To ensure your consultation is personalized and productive, please share a few details about your project below. Our team will review and follow up within 1–2 business days.
                                </span>
                              </div>
                            </div>
                          </div>
                          <div className="flex">
                            <div className="w-full flex flex-col justify-center items-center gap-3 [filter:blur(0px)]" data-ditto-id="style-link-4">
                              <div className="flex flex-col gap-2 max-md:hidden">
                                <button className="h-10 flex relative isolate p-2 rounded-lg justify-center items-center text-clr-21 font-semibold text-center bg-clr-22 cursor-pointer before:content-[''] before:block before:absolute before:inset-0 before:w-[120.109px] before:h-10 before:bg-clr-23 before:rounded-tl-lg max-md:before:w-full max-md:before:h-full max-md:before:right-auto max-md:before:bottom-auto after:content-[''] after:block after:absolute after:inset-0 after:w-[120.109px] after:h-10 after:shadow-[var(--clr-23)_0px_0px_0px_1px_inset] after:rounded-tl-lg max-md:after:w-full max-md:after:h-full max-md:after:right-auto max-md:after:bottom-auto" data-ditto-id="style-link-5" data-component="button">
                                  <span className="block z-1 px-2 justify-center text-lg leading-6" data-ditto-id="style-account">
                                    Start
                                  </span>
                                </button>
                                <div className="flex justify-center items-center gap-1 [filter:blur(0px)]">
                                  <svg className="w-auto h-3 block overflow-hidden" data-ditto-id="style-cart" data-component="icon" fill="none" height="12" viewBox="0 0 12 12" width="12" data-qa="animated-clock">
                                    <g transform="translate(6, 6) translate(0, 0)">
                                      <path id="clock-hour-hand" stroke="#000000" strokeLinecap="round" strokeLinejoin="round" fill="none" strokeWidth="1.5" strokeOpacity="1" d=" M1.56 1.56 C1.56,1.56 0,0 0,0 " />
                                    </g>
                                    <g transform="translate(6, 6) translate(0, 0)">
                                      <path stroke="#000000" strokeLinecap="round" strokeLinejoin="round" fill="none" strokeWidth="1.5" strokeOpacity="1" d=" M0 0 C0,0 0,-2.35 0,-2.35 " />
                                    </g>
                                    <g transform="translate(6, 6) translate(0, 0)">
                                      <path stroke="#000000" strokeLinecap="round" strokeLinejoin="round" fill="none" strokeWidth="1.5" strokeOpacity="1" d=" M0 5.25 C2.9,5.25 5.25,2.9 5.25,0 C5.25,-2.9 2.9,-5.25 0,-5.25 C-2.9,-5.25 -5.25,-2.9 -5.25,0 C-5.25,2.9 -2.9,5.25 0,5.25z " />
                                    </g>
                                  </svg>
                                  <div className="flex gap-1 text-color-023">
                                    <span className="block leading-4.5">
                                      Takes 2 minutes
                                    </span>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </fieldset>
                      </div>
                    </div>
                  </main>
                  <footer className="h-8 flex absolute right-0 bottom-0 left-312 z-50 min-w-0 pr-8 pb-8 justify-end max-md:h-29 max-md:left-0 max-md:py-4 max-md:pl-8 max-md:[backdrop-filter:blur(16px)] md:max-lg:left-184 2xl:left-472" data-ditto-id="style-shopify-section-template-20207705292962-main" />
                </div>
                <div className="w-full block absolute top-196 bottom-4 left-4 z-1100 min-w-0 max-md:relative max-md:inset-0 max-md:max-h-0 max-md:bg-color-022" />
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="w-7 h-4 block absolute -top-[6249.9375rem] -left-[6249.9375rem] leading-[1.0625rem] whitespace-nowrap">
        Mgy
      </div>
    </>
  );
}
