import "./ditto.css";
import MediaTile from "./components/media-tile";
import MediaTile2 from "./components/media-tile2";
import FeatureCard from "./components/feature-card";
// Generated by clone-site. Do not edit by hand.
const MediaTile_data = [
    { ariaLabel: "Add Herringbone Haze swatch to cart", alt: "Herringbone Haze swatch", imgSrc: "/assets/cloned/images/5eaf5eeb1a90.jpg", text: "Herringbone Haze" },
    { ariaLabel: "Add Herringbone Saffron swatch to cart", alt: "Herringbone Saffron swatch", imgSrc: "/assets/cloned/images/075e6726f4d5.jpg", text: "Herringbone Saffron" },
    { ariaLabel: "Add Windsor Diamond Magnolia swatch to cart", alt: "Windsor Diamond Magnolia swatch", imgSrc: "/assets/cloned/images/410a92f1da63.jpg", text: "Windsor Diamond Magnolia" },
    { ariaLabel: "Add Windsor Diamond Parchment swatch to cart", alt: "Windsor Diamond Parchment swatch", imgSrc: "/assets/cloned/images/132198653b9d.jpg", text: "Windsor Diamond Parchment" },
    { ariaLabel: "Add Manor Linen Gardenia swatch to cart", alt: "Manor Linen Gardenia swatch", imgSrc: "/assets/cloned/images/cf60cd0ca5d0.jpg", text: "Manor Linen Gardenia" },
    { ariaLabel: "Add Manor Linen Limestone swatch to cart", alt: "Manor Linen Limestone swatch", imgSrc: "/assets/cloned/images/04b59551862b.jpg", text: "Manor Linen Limestone" },
    { ariaLabel: "Add Manor Linen Mist swatch to cart", alt: "Manor Linen Mist swatch", imgSrc: "/assets/cloned/images/25a9340197a4.png", text: "Manor Linen Mist" },
    { ariaLabel: "Add Manor Linen Citrine swatch to cart", alt: "Manor Linen Citrine swatch", imgSrc: "/assets/cloned/images/a429330aa505.jpg", text: "Manor Linen Citrine" },
    { ariaLabel: "Add Magnolia Sheer swatch to cart", alt: "Magnolia Sheer swatch", imgSrc: "/assets/cloned/images/17dddcb24138.jpg", text: "Magnolia Sheer" },
    { ariaLabel: "Add Parchment Sheer swatch to cart", alt: "Parchment Sheer swatch", imgSrc: "/assets/cloned/images/2569a04a405e.png", text: "Parchment Sheer" },
    { ariaLabel: "Add Parlor Stripe Sheer swatch to cart", alt: "Parlor Stripe Sheer swatch", imgSrc: "/assets/cloned/images/4b949104de5a.jpg", text: "Parlor Stripe Sheer" },
    { ariaLabel: "Add Sudare Kurumi swatch to cart", alt: "Sudare Kurumi swatch", imgSrc: "/assets/cloned/images/ba6fcbb619be.jpg", text: "Sudare Kurumi" },
    { ariaLabel: "Add Sudare Kurumi + Willow Trim swatch to cart", alt: "Sudare Kurumi + Willow Trim swatch", imgSrc: "/assets/cloned/images/9bc865b14fe1.jpg", text: "Sudare Kurumi + Willow Trim" },
    { ariaLabel: "Add Sudare Kurumi + Medallion Trim swatch to cart", ariadisabled: "true", alt: "Sudare Kurumi + Medallion Trim swatch", imgSrc: "/assets/cloned/images/8d079d2cd1b5.jpg", text: "Sudare Kurumi + Medallion Trim", disabled: true },
    { ariaLabel: "Add Sudare Kurumi + Lotus Trim swatch to cart", alt: "Sudare Kurumi + Lotus Trim swatch", imgSrc: "/assets/cloned/images/13aae79562e5.jpg", text: "Sudare Kurumi + Lotus Trim" }
];
const MediaTile2_data = [
    { ariaLabel: "Add Quartz swatch to cart", alt: "Quartz swatch", imgSrc: "/assets/cloned/images/277c69a6f587.png", text: "Quartz" },
    { ariaLabel: "Add Driftwood swatch to cart", alt: "Driftwood swatch", imgSrc: "/assets/cloned/images/1913bd6ceebd.png", text: "Driftwood" },
    { ariaLabel: "Add Flax swatch to cart", alt: "Flax swatch", imgSrc: "/assets/cloned/images/5b57972c7a61.png", text: "Flax" },
    { ariaLabel: "Add Granite swatch to cart", alt: "Granite swatch", imgSrc: "/assets/cloned/images/1bed47139219.png", text: "Granite" },
    { ariaLabel: "Add Umber swatch to cart", alt: "Umber swatch", imgSrc: "/assets/cloned/images/afc81d301c96.png", text: "Umber" },
    { ariaLabel: "Add Cognac swatch to cart", alt: "Cognac swatch", imgSrc: "/assets/cloned/images/3b09dff3ab7d.png", text: "Cognac" },
    { ariaLabel: "Add Juniper swatch to cart", alt: "Juniper swatch", imgSrc: "/assets/cloned/images/d4401045e2eb.png", text: "Juniper" }
];
const MediaTile2_data2 = [
    { ariaLabel: "Add Moon swatch to cart", alt: "Moon swatch", imgSrc: "/assets/cloned/images/eecc6ba0a8c8.jpg", text: "Moon" },
    { ariaLabel: "Add Bone swatch to cart", alt: "Bone swatch", imgSrc: "/assets/cloned/images/99db551ebe7a.jpg", text: "Bone" },
    { ariaLabel: "Add Sand swatch to cart", alt: "Sand swatch", imgSrc: "/assets/cloned/images/3a34ed1ab664.jpg", text: "Sand" },
    { ariaLabel: "Add Birch swatch to cart", alt: "Birch swatch", imgSrc: "/assets/cloned/images/70f6df58c274.jpg", text: "Birch" },
    { ariaLabel: "Add Ash swatch to cart", alt: "Ash swatch", imgSrc: "/assets/cloned/images/4d00bcf6f84a.jpg", text: "Ash" },
    { ariaLabel: "Add Sage swatch to cart", alt: "Sage swatch", imgSrc: "/assets/cloned/images/54f9c1c78cf6.jpg", text: "Sage" },
    { ariaLabel: "Add Rose swatch to cart", alt: "Rose swatch", imgSrc: "/assets/cloned/images/decd58afd442.jpg", text: "Rose" },
    { ariaLabel: "Add Storm swatch to cart", alt: "Storm swatch", imgSrc: "/assets/cloned/images/7f984c65921d.png", text: "Storm" }
];
const MediaTile2_data3 = [
    { ariaLabel: "Add Moon Sheers swatch to cart", alt: "Moon Sheers swatch", imgSrc: "/assets/cloned/images/083c0005dfe9.jpg", text: "Moon Sheers" },
    { ariaLabel: "Add Bone Sheers swatch to cart", alt: "Bone Sheers swatch", imgSrc: "/assets/cloned/images/8233f083c7df.jpg", text: "Bone Sheers" },
    { ariaLabel: "Add Pebble Sheers swatch to cart", alt: "Pebble Sheers swatch", imgSrc: "/assets/cloned/images/7a83d19f6425.jpg", text: "Pebble Sheers" }
];
const MediaTile2_data4 = [
    { ariaLabel: "Add Ivory swatch to cart", alt: "Ivory swatch", imgSrc: "/assets/cloned/images/72d7bd026384.jpg", text: "Ivory" },
    { ariaLabel: "Add Oyster swatch to cart", alt: "Oyster swatch", imgSrc: "/assets/cloned/images/60b3e7b8bd85.jpg", text: "Oyster" },
    { ariaLabel: "Add Denim swatch to cart", alt: "Denim swatch", imgSrc: "/assets/cloned/images/76ab1f7af890.jpg", text: "Denim" },
    { ariaLabel: "Add Petal swatch to cart", alt: "Petal swatch", imgSrc: "/assets/cloned/images/9c5b2c5063b7.jpg", text: "Petal" }
];
const MediaTile2_data5 = [
    { ariaLabel: "Add Seashell swatch to cart", alt: "Seashell swatch", imgSrc: "/assets/cloned/images/a09454bae30e.jpg", text: "Seashell" },
    { ariaLabel: "Add Khaki swatch to cart", alt: "Khaki swatch", imgSrc: "/assets/cloned/images/72471319a778.jpg", text: "Khaki" },
    { ariaLabel: "Add Chestnut swatch to cart", alt: "Chestnut swatch", imgSrc: "/assets/cloned/images/d5f9ac044efd.jpg", text: "Chestnut" },
    { ariaLabel: "Add Cocoa swatch to cart", alt: "Cocoa swatch", imgSrc: "/assets/cloned/images/6dd537f20f2a.jpg", text: "Cocoa" },
    { ariaLabel: "Add Onyx swatch to cart", alt: "Onyx swatch", imgSrc: "/assets/cloned/images/8f693c745ee0.jpg", text: "Onyx" }
];
const MediaTile2_data6 = [
    { ariaLabel: "Add Paisley swatch to cart", alt: "Paisley swatch", imgSrc: "/assets/cloned/images/fb68b6ff5933.jpg", text: "Paisley" },
    { ariaLabel: "Add Margueritte swatch to cart", alt: "Margueritte swatch", imgSrc: "/assets/cloned/images/5a66c793bd99.jpg", text: "Margueritte" },
    { ariaLabel: "Add Grace Stripe swatch to cart", alt: "Grace Stripe swatch", imgSrc: "/assets/cloned/images/36150b91042f.jpg", text: "Grace Stripe" },
    { ariaLabel: "Add Blythe Sheer swatch to cart", alt: "Blythe Sheer swatch", imgSrc: "/assets/cloned/images/5aaae89ba44a.jpg", text: "Blythe Sheer" }
];
const MediaTile2_data7 = [
    { ariaLabel: "Add Starry Moons swatch to cart", alt: "Starry Moons swatch", imgSrc: "/assets/cloned/images/a9ad98aad70c.webp", text: "Starry Moons" },
    { ariaLabel: "Add Winking Diamonds swatch to cart", alt: "Winking Diamonds swatch", imgSrc: "/assets/cloned/images/08210bcb428d.webp", text: "Winking Diamonds" },
    { ariaLabel: "Add Dainty Rose swatch to cart", alt: "Dainty Rose swatch", imgSrc: "/assets/cloned/images/873647c01662.webp", text: "Dainty Rose" },
    { ariaLabel: "Add Circus Circus swatch to cart", alt: "Circus Circus swatch", imgSrc: "/assets/cloned/images/c2de26acf9ad.webp", text: "Circus Circus" }
];
const MediaTile2_data8 = [
    { ariaLabel: "Add Pearl Privacy swatch to cart", alt: "Pearl Privacy swatch", imgSrc: "/assets/cloned/images/12b8e7e9a842.webp", text: "Pearl Privacy" },
    { ariaLabel: "Add Ecru Privacy swatch to cart", alt: "Ecru Privacy swatch", imgSrc: "/assets/cloned/images/03bf67aad7e2.webp", text: "Ecru Privacy" },
    { ariaLabel: "Add Stone Privacy swatch to cart", alt: "Stone Privacy swatch", imgSrc: "/assets/cloned/images/c7707da438e6.webp", text: "Stone Privacy" },
    { ariaLabel: "Add Wheat Privacy swatch to cart", alt: "Wheat Privacy swatch", imgSrc: "/assets/cloned/images/ada5c919fa95.webp", text: "Wheat Privacy" },
    { ariaLabel: "Add Pearl Blackout swatch to cart", alt: "Pearl Blackout swatch", imgSrc: "/assets/cloned/images/f6c4cbba852f.webp", text: "Pearl Blackout" },
    { ariaLabel: "Add Ecru Blackout swatch to cart", alt: "Ecru Blackout swatch", imgSrc: "/assets/cloned/images/03bf67aad7e2.webp", text: "Ecru Blackout" },
    { ariaLabel: "Add Stone Blackout swatch to cart", alt: "Stone Blackout swatch", imgSrc: "/assets/cloned/images/c7707da438e6.webp", text: "Stone Blackout" },
    { ariaLabel: "Add Wheat Blackout swatch to cart", alt: "Wheat Blackout swatch", imgSrc: "/assets/cloned/images/ada5c919fa95.webp", text: "Wheat Blackout" }
];
const FeatureCard_data = [
    { text: "01", title: "Select your swatches.", description: "Choose up to 5 free materials to compare in your own space." },
    { text: "02", title: "Hold them in your home.", description: "Experience the texture and color throughout the day, in your light and alongside the pieces you already live with." },
    { text: "03", title: "Order with confidence.", description: "Once you’re ready, configure your windows knowing exactly how the fabric will feel in your home." }
];
const MediaTile_meta: string[][] = [
    ["n50", "n51", "style-button", "style-button-2"],
    ["n54", "n55", "n56", "n57"],
    ["n58", "n59", "style-div-2", "n61"],
    ["style-div-3", "n63", "style-div-4", "n65"],
    ["style-shopify-section-template-20207706308770-tabs", "n67", "style-div-5", "n69"],
    ["style-div-6", "n71", "n72", "n73"],
    ["n74", "style-p", "n76", "style-div-7"],
    ["n78", "style-div-8", "n80", "style-shades-guide-top"],
    ["n82", "n83", "n84", "n85"],
    ["style-link-8", "n87", "style-link-9", "n89"],
    ["n90", "n91", "n92", "style-link-10"],
    ["n94", "style-link-11", "n96", "n97"],
    ["n98", "n99", "n100", "n101"],
    ["style-subscribe", "n103", "n104", "style-div"],
    ["n106", "style-shades-guide-shade-type", "n108", "style-header"]
];
const MediaTile2_meta: string[][] = [
    ["n130", "n131", "n132", "n133"],
    ["n134", "n135", "n136", "n137"],
    ["n138", "n139", "n140", "n141"],
    ["n142", "n143", "n144", "n145"],
    ["n146", "n147", "n148", "n149"],
    ["n150", "n151", "n152", "n153"],
    ["n154", "n155", "n156", "n157"]
];
const MediaTile2_meta2: string[][] = [
    ["n166", "n167", "n168", "n169"],
    ["n170", "n171", "n172", "n173"],
    ["n174", "n175", "n176", "n177"],
    ["n178", "n179", "n180", "n181"],
    ["n182", "n183", "n184", "n185"],
    ["n186", "n187", "n188", "n189"],
    ["n190", "n191", "n192", "n193"],
    ["n194", "n195", "n196", "n197"]
];
const MediaTile2_meta3: string[][] = [
    ["n206", "n207", "n208", "n209"],
    ["n210", "n211", "n212", "n213"],
    ["n214", "n215", "n216", "n217"]
];
const MediaTile2_meta4: string[][] = [
    ["n226", "n227", "n228", "n229"],
    ["n230", "n231", "n232", "n233"],
    ["n234", "n235", "n236", "n237"],
    ["n238", "n239", "n240", "n241"]
];
const MediaTile2_meta5: string[][] = [
    ["n250", "n251", "n252", "n253"],
    ["n254", "n255", "n256", "n257"],
    ["n258", "n259", "n260", "n261"],
    ["n262", "n263", "n264", "n265"],
    ["n266", "n267", "n268", "n269"]
];
const MediaTile2_meta6: string[][] = [
    ["n278", "n279", "n280", "n281"],
    ["n282", "n283", "n284", "n285"],
    ["n286", "n287", "n288", "n289"],
    ["n290", "n291", "n292", "n293"]
];
const MediaTile2_meta7: string[][] = [
    ["n302", "n303", "n304", "n305"],
    ["n306", "n307", "n308", "n309"],
    ["n310", "n311", "n312", "n313"],
    ["n314", "n315", "n316", "n317"]
];
const MediaTile2_meta8: string[][] = [
    ["n326", "n327", "n328", "n329"],
    ["n330", "n331", "n332", "n333"],
    ["n334", "n335", "n336", "n337"],
    ["n338", "n339", "n340", "n341"],
    ["n342", "n343", "n344", "n345"],
    ["n346", "n347", "n348", "n349"],
    ["n350", "n351", "n352", "n353"],
    ["n354", "n355", "n356", "n357"]
];
const FeatureCard_meta: string[][] = [
    ["n365", "n366", "n367", "n368", "n369", "n370"],
    ["n371", "n372", "n373", "n374", "n375", "n376"],
    ["n377", "n378", "n379", "n380", "n381", "n382"]
];
const MediaTile_styles = [
    { className: "cursor-pointer" },
    { className: "cursor-pointer" },
    { className: "cursor-pointer" },
    { className: "cursor-pointer" },
    { className: "cursor-pointer" },
    { className: "cursor-pointer" },
    { className: "cursor-pointer" },
    { className: "cursor-pointer" },
    { className: "cursor-pointer" },
    { className: "cursor-pointer" },
    { className: "cursor-pointer" },
    { className: "cursor-pointer" },
    { className: "cursor-pointer" },
    { className: "opacity-45 cursor-default", className2: "opacity-45" },
    { className: "cursor-pointer" }
];
const FeatureCard_styles = [
    { className: "border-b border-solid border-b-primary pb-8" },
    { className: "border-b border-solid border-b-primary pb-8" },
    {  }
];

export default function Page() {
  return (
    <>
      <section className="grid relative grid-cols-[minmax(20px,1fr)_minmax(0,1400px)_minmax(20px,1fr)] max-md:grid-cols-[16px_343px_16px] md:max-lg:grid-cols-[16px_736px_16px]" data-ditto-id="style-shopify-section-template-20207705292962-main" aria-hidden="true" id="shopify-section-template--20207706636450__everhem_swatches_collection_new_M8Wrrc">
        <section className="block col-span-full bg-background">
          <div className="h-[clamp(422.39px,_55vh,_560px)] block relative overflow-hidden bg-accent">
            <img className="w-full h-full block absolute top-0 left-0 max-w-full overflow-clip object-cover aspect-[auto_2400/1200]" data-component="image" alt="See it in your space, then decide." height="1200" src="/assets/cloned/images/eb801b888854.jpg" width="2400" />
            {" "}
            <div className="h-full block absolute top-0 inset-x-0 pointer-events-none" style={{ backgroundImage: "linear-gradient(var(--clr-12), var(--clr-7) 40%)" }} aria-hidden="true" />
            {" "}
          </div>
          <div className="block max-w-350 py-11 px-8 max-lg:py-8 max-md:px-4 md:max-lg:px-6">
            <header className="w-full max-w-176 flex mb-12 flex-col gap-2">
              <h1 className="block [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-5xl font-light italic leading-[3.0625rem] tracking-[-0.48px] [overflow-wrap:break-word] max-lg:text-4xl max-lg:leading-[2.3125rem] max-lg:tracking-[-0.36px]" data-component="heading">
                See it in your space, then decide.
              </h1>
              <p className="block text-color-002 text-xs font-medium leading-[1.1875rem] tracking-[1.44px] uppercase [overflow-wrap:break-word]">
                Order up to 5 free swatches, just pay shipping.
              </p>
            </header>
            <div className="flex flex-col gap-16">
              <section className="border-t border-solid border-t-primary grid pt-5 flex-col items-start gap-[2.4rem] grid-cols-[1fr_1.35fr] max-lg:gap-5 max-lg:grid-cols-1" id="jake-arnold-for-everhem">
                <figure className="block overflow-hidden bg-accent aspect-[0.8] max-lg:aspect-[4/3]">
                  <img className="w-full h-156.5 block max-w-full overflow-clip object-cover aspect-[auto_1200/1500] max-md:h-64 md:max-lg:h-[33.8125rem]" data-ditto-id="style-link-6" data-component="image" alt="Jake Arnold for Everhem" height="1500" src="/assets/cloned/images/6e2468160ac7.webp" width="1200" />
                  {" "}
                </figure>
                <div className="flex min-w-0 flex-col gap-5" data-ditto-id="style-link-7">
                  <header className="flex flex-wrap items-baseline gap-4">
                    <h2 className="block [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-[2.1875rem] font-light italic leading-[2.3125rem] tracking-[-0.35px] [overflow-wrap:break-word] max-lg:text-[1.75rem] max-lg:leading-[1.8125rem] max-lg:tracking-[-0.28px]" data-component="heading">
                      Jake Arnold for Everhem
                    </h2>
                    <p className="block text-color-004 text-sm leading-[1.375rem] [overflow-wrap:break-word]">
                      15 curated materials
                    </p>
                  </header>
                  {" "}
                  <div className="grid gap-4 grid-cols-[repeat(auto-fit,_minmax(156px,_1fr))]">
                    {MediaTile_data.map((d, i) => <MediaTile key={i} d={d} styles={MediaTile_styles[i]} />)}
                  </div>
                  {" "}
                </div>
                {" "}
              </section>
              <section className="border-t border-solid border-t-primary grid pt-5 flex-col items-start gap-[2.4rem] grid-cols-[1.35fr_1fr] max-lg:gap-5 max-lg:grid-cols-1" id="this-oak-house-for-everhem">
                <figure className="block order-[2] overflow-hidden bg-accent aspect-[0.8] max-lg:aspect-[4/3] max-lg:order-[initial]">
                  <img className="w-full h-156.5 block max-w-full overflow-clip object-cover aspect-[auto_1200/1500] max-md:h-64 md:max-lg:h-[33.8125rem]" data-component="image" alt="This Oak House for Everhem" height="1500" src="/assets/cloned/images/e9ddb21685d9.webp" width="1200" />
                  {" "}
                </figure>
                <div className="flex min-w-0 flex-col gap-5">
                  <header className="flex flex-wrap items-baseline gap-4">
                    <h2 className="block [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-[2.1875rem] font-light italic leading-[2.3125rem] tracking-[-0.35px] [overflow-wrap:break-word] max-lg:text-[1.75rem] max-lg:leading-[1.8125rem] max-lg:tracking-[-0.28px]" data-component="heading">
                      This Oak House for Everhem
                    </h2>
                    <p className="block text-color-004 text-sm leading-[1.375rem] [overflow-wrap:break-word]">
                      100% Bamboo
                    </p>
                  </header>
                  {" "}
                  <div className="grid gap-4 grid-cols-[repeat(auto-fit,_minmax(156px,_1fr))]">
                    <div className="flex relative flex-col items-stretch gap-1 text-left cursor-pointer" data-component="button" aria-label="Add Oak Matchstick swatch to cart" role="button">
                      <img className="w-full h-[9.8125rem] border border-solid border-primary block max-w-full overflow-clip object-cover aspect-square max-md:h-41 md:max-lg:h-42" data-component="image" alt="Oak Matchstick swatch" height="400" src="/assets/cloned/images/173e28efe31b.jpg" width="400" />
                      <span className="block text-sm leading-[1.125rem]">
                        Oak Matchstick
                      </span>
                      {" "}
                      <button className="block text-color-002 text-xs font-medium leading-3 tracking-[1.44px] uppercase" data-component="button" type="button">
                        Add swatch
                      </button>
                      {" "}
                    </div>
                  </div>
                  {" "}
                </div>
                {" "}
              </section>
              <section className="border-t border-solid border-t-primary grid pt-5 flex-col items-start gap-[2.4rem] grid-cols-[1fr_1.35fr] max-lg:gap-5 max-lg:grid-cols-1" id="linen-cotton-copy">
                <figure className="block overflow-hidden bg-accent aspect-[0.8] max-lg:aspect-[4/3]">
                  <img className="w-full h-156.5 block max-w-full overflow-clip object-cover aspect-[auto_1200/1500] max-md:h-64 md:max-lg:h-[33.8125rem]" data-component="image" alt="Linen — Everhem Hues" height="1500" src="/assets/cloned/images/fffcf582c4e1.webp" width="1200" />
                  {" "}
                </figure>
                <div className="flex min-w-0 flex-col gap-5">
                  <header className="flex flex-wrap items-baseline gap-4">
                    <h2 className="block [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-[2.1875rem] font-light italic leading-[2.3125rem] tracking-[-0.35px] [overflow-wrap:break-word] max-lg:text-[1.75rem] max-lg:leading-[1.8125rem] max-lg:tracking-[-0.28px]" data-component="heading">
                      Linen — Everhem Hues
                    </h2>
                    <p className="block text-color-004 text-sm leading-[1.375rem] [overflow-wrap:break-word]">
                      100% Belgian Linen
                    </p>
                  </header>
                  {" "}
                  <div className="grid gap-4 grid-cols-[repeat(auto-fit,_minmax(156px,_1fr))] grid-rows-2 max-md:grid-rows-4">
                    {MediaTile2_data.map((d, i) => <MediaTile2 key={i} d={d} />)}
                  </div>
                  {" "}
                </div>
                {" "}
              </section>
              <section className="border-t border-solid border-t-primary grid pt-5 flex-col items-start gap-[2.4rem] grid-cols-[1.35fr_1fr] max-lg:gap-5 max-lg:grid-cols-1" id="linen-cotton">
                <figure className="block order-[2] overflow-hidden bg-accent aspect-[0.8] max-lg:aspect-[4/3] max-lg:order-[initial]">
                  <img className="w-full h-156.5 block max-w-full overflow-clip object-cover aspect-[auto_1200/1500] max-md:h-64 md:max-lg:h-[33.8125rem]" data-component="image" alt="Linen Cotton — Everhem Essentials" height="1500" src="/assets/cloned/images/42a9bbdc58f4.webp" width="1200" />
                  {" "}
                </figure>
                <div className="flex min-w-0 flex-col gap-5">
                  <header className="flex flex-wrap items-baseline gap-4">
                    <h2 className="block [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-[2.1875rem] font-light italic leading-[2.3125rem] tracking-[-0.35px] [overflow-wrap:break-word] max-lg:text-[1.75rem] max-lg:leading-[1.8125rem] max-lg:tracking-[-0.28px]" data-component="heading">
                      Linen Cotton — Everhem Essentials
                    </h2>
                    <p className="block text-color-004 text-sm leading-[1.375rem] [overflow-wrap:break-word]">
                      65% Linen, 35% Cotton
                    </p>
                  </header>
                  {" "}
                  <div className="grid gap-4 grid-cols-[repeat(auto-fit,_minmax(156px,_1fr))] grid-rows-2 max-md:grid-rows-4">
                    {MediaTile2_data2.map((d, i) => <MediaTile2 key={i} d={d} />)}
                  </div>
                  {" "}
                </div>
                {" "}
              </section>
              <section className="border-t border-solid border-t-primary grid pt-5 flex-col items-start gap-[2.4rem] grid-cols-[1fr_1.35fr] max-lg:gap-5 max-lg:grid-cols-1" id="sheers">
                <figure className="block overflow-hidden bg-accent aspect-[0.8] max-lg:aspect-[4/3]">
                  <img className="w-full h-156.5 block max-w-full overflow-clip object-cover aspect-[auto_1200/1500] max-md:h-64 md:max-lg:h-[33.8125rem]" data-component="image" alt="Sheers" height="1500" src="/assets/cloned/images/a1148687806c.webp" width="1200" />
                  {" "}
                </figure>
                <div className="flex min-w-0 flex-col gap-5">
                  <header className="flex flex-wrap items-baseline gap-4">
                    <h2 className="block [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-[2.1875rem] font-light italic leading-[2.3125rem] tracking-[-0.35px] [overflow-wrap:break-word] max-lg:text-[1.75rem] max-lg:leading-[1.8125rem] max-lg:tracking-[-0.28px]" data-component="heading">
                      Sheers
                    </h2>
                    <p className="block text-color-004 text-sm leading-[1.375rem] [overflow-wrap:break-word]">
                      54% Linen, 32% Cotton, 14% Polyester
                    </p>
                  </header>
                  {" "}
                  <div className="grid gap-4 grid-cols-[repeat(auto-fit,_minmax(156px,_1fr))]">
                    {MediaTile2_data3.map((d, i) => <MediaTile2 key={i} d={d} />)}
                  </div>
                  {" "}
                </div>
                {" "}
              </section>
              <section className="border-t border-solid border-t-primary grid pt-5 flex-col items-start gap-[2.4rem] grid-cols-[1.35fr_1fr] max-lg:gap-5 max-lg:grid-cols-1" id="cotton-stripes">
                <figure className="block order-[2] overflow-hidden bg-accent aspect-[0.8] max-lg:aspect-[4/3] max-lg:order-[initial]">
                  <img className="w-full h-156.5 block max-w-full overflow-clip object-cover aspect-[auto_1200/1500] max-md:h-64 md:max-lg:h-[33.8125rem]" data-component="image" alt="Cotton — Stripes" height="1500" src="/assets/cloned/images/418ca77378fd.webp" width="1200" />
                  {" "}
                </figure>
                <div className="flex min-w-0 flex-col gap-5">
                  <header className="flex flex-wrap items-baseline gap-4">
                    <h2 className="block [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-[2.1875rem] font-light italic leading-[2.3125rem] tracking-[-0.35px] [overflow-wrap:break-word] max-lg:text-[1.75rem] max-lg:leading-[1.8125rem] max-lg:tracking-[-0.28px]" data-component="heading">
                      Cotton — Stripes
                    </h2>
                    <p className="block text-color-004 text-sm leading-[1.375rem] [overflow-wrap:break-word]">
                      100% Washed Cotton
                    </p>
                  </header>
                  {" "}
                  <div className="grid gap-4 grid-cols-[repeat(auto-fit,_minmax(156px,_1fr))]">
                    {MediaTile2_data4.map((d, i) => <MediaTile2 key={i} d={d} />)}
                  </div>
                  {" "}
                </div>
                {" "}
              </section>
              <section className="border-t border-solid border-t-primary grid pt-5 flex-col items-start gap-[2.4rem] grid-cols-[1fr_1.35fr] max-lg:gap-5 max-lg:grid-cols-1" id="classic-woven-woods">
                <figure className="block overflow-hidden bg-accent aspect-[0.8] max-lg:aspect-[4/3]">
                  <img className="w-full h-156.5 block max-w-full overflow-clip object-cover aspect-[auto_1200/1500] max-md:h-64 md:max-lg:h-[33.8125rem]" data-component="image" alt="Classic Woven Woods" height="1500" src="/assets/cloned/images/0416f2adcd3d.webp" width="1200" />
                  {" "}
                </figure>
                <div className="flex min-w-0 flex-col gap-5">
                  <header className="flex flex-wrap items-baseline gap-4">
                    <h2 className="block [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-[2.1875rem] font-light italic leading-[2.3125rem] tracking-[-0.35px] [overflow-wrap:break-word] max-lg:text-[1.75rem] max-lg:leading-[1.8125rem] max-lg:tracking-[-0.28px]" data-component="heading">
                      Classic Woven Woods
                    </h2>
                    <p className="block text-color-004 text-sm leading-[1.375rem] [overflow-wrap:break-word]">
                      {"100% Natural Reeds & Grasses"}
                    </p>
                  </header>
                  {" "}
                  <div className="grid gap-4 grid-cols-[repeat(auto-fit,_minmax(156px,_1fr))] grid-rows-2 max-md:grid-rows-3">
                    {MediaTile2_data5.map((d, i) => <MediaTile2 key={i} d={d} />)}
                  </div>
                  {" "}
                </div>
                {" "}
              </section>
              <section className="border-t border-solid border-t-primary grid pt-5 flex-col items-start gap-[2.4rem] grid-cols-[1.35fr_1fr] max-lg:gap-5 max-lg:grid-cols-1" id="amber-lewis-x-everhem">
                <figure className="block order-[2] overflow-hidden bg-accent aspect-[0.8] max-lg:aspect-[4/3] max-lg:order-[initial]">
                  <img className="w-full h-156.5 block max-w-full overflow-clip object-cover aspect-[auto_1200/1500] max-md:h-64 md:max-lg:h-[33.8125rem]" data-component="image" alt="Amber Lewis x Everhem" height="1500" src="/assets/cloned/images/d5c17fdfb54d.webp" width="1200" />
                  {" "}
                </figure>
                <div className="flex min-w-0 flex-col gap-5">
                  <header className="flex flex-wrap items-baseline gap-4">
                    <h2 className="block [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-[2.1875rem] font-light italic leading-[2.3125rem] tracking-[-0.35px] [overflow-wrap:break-word] max-lg:text-[1.75rem] max-lg:leading-[1.8125rem] max-lg:tracking-[-0.28px]" data-component="heading">
                      Amber Lewis x Everhem
                    </h2>
                    <p className="block text-color-004 text-sm leading-[1.375rem] [overflow-wrap:break-word]">
                      Custom patterns on linen and cotton
                    </p>
                  </header>
                  {" "}
                  <div className="grid gap-4 grid-cols-[repeat(auto-fit,_minmax(156px,_1fr))]">
                    {MediaTile2_data6.map((d, i) => <MediaTile2 key={i} d={d} />)}
                  </div>
                  {" "}
                </div>
                {" "}
              </section>
              <section className="border-t border-solid border-t-primary grid pt-5 flex-col items-start gap-[2.4rem] grid-cols-[1fr_1.35fr] max-lg:gap-5 max-lg:grid-cols-1" id="carly-kuhn-collection">
                <figure className="block overflow-hidden bg-accent aspect-[0.8] max-lg:aspect-[4/3]">
                  <img className="w-full h-156.5 block max-w-full overflow-clip object-cover aspect-[auto_1200/1500] max-md:h-64 md:max-lg:h-[33.8125rem]" data-component="image" alt="Carly Kuhn Collection" height="1500" src="/assets/cloned/images/46f2a596a19c.webp" width="1200" />
                  {" "}
                </figure>
                <div className="flex min-w-0 flex-col gap-5">
                  <header className="flex flex-wrap items-baseline gap-4">
                    <h2 className="block [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-[2.1875rem] font-light italic leading-[2.3125rem] tracking-[-0.35px] [overflow-wrap:break-word] max-lg:text-[1.75rem] max-lg:leading-[1.8125rem] max-lg:tracking-[-0.28px]" data-component="heading">
                      Carly Kuhn Collection
                    </h2>
                    <p className="block text-color-004 text-sm leading-[1.375rem] [overflow-wrap:break-word]">
                      95% Cotton, 5% Linen
                    </p>
                  </header>
                  {" "}
                  <div className="grid gap-4 grid-cols-[repeat(auto-fit,_minmax(156px,_1fr))]">
                    {MediaTile2_data7.map((d, i) => <MediaTile2 key={i} d={d} />)}
                  </div>
                  {" "}
                </div>
                {" "}
              </section>
              <section className="border-t border-solid border-t-primary grid pt-5 flex-col items-start gap-[2.4rem] grid-cols-[1.35fr_1fr] max-lg:gap-5 max-lg:grid-cols-1" id="roller-shade-essentials">
                <figure className="block order-[2] overflow-hidden bg-accent aspect-[0.8] max-lg:aspect-[4/3] max-lg:order-[initial]">
                  <img className="w-full h-156.5 block max-w-full overflow-clip object-cover aspect-[auto_1200/1500] max-md:h-64 md:max-lg:h-[33.8125rem]" data-component="image" alt="Roller Shade Essentials" height="1500" src="/assets/cloned/images/8a448a976b5f.webp" width="1200" />
                  {" "}
                </figure>
                <div className="flex min-w-0 flex-col gap-5">
                  <header className="flex flex-wrap items-baseline gap-4">
                    <h2 className="block [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-[2.1875rem] font-light italic leading-[2.3125rem] tracking-[-0.35px] [overflow-wrap:break-word] max-lg:text-[1.75rem] max-lg:leading-[1.8125rem] max-lg:tracking-[-0.28px]" data-component="heading">
                      Roller Shade Essentials
                    </h2>
                    <p className="block text-color-004 text-sm leading-[1.375rem] [overflow-wrap:break-word]">
                      100% Polyester
                    </p>
                  </header>
                  {" "}
                  <div className="grid gap-4 grid-cols-[repeat(auto-fit,_minmax(156px,_1fr))] grid-rows-2 max-md:grid-rows-4">
                    {MediaTile2_data8.map((d, i) => <MediaTile2 key={i} d={d} />)}
                  </div>
                  {" "}
                </div>
                {" "}
              </section>
            </div>
            {" "}
          </div>
          {" "}
        </section>
        {" "}
      </section>
      <section className="grid relative grid-cols-[minmax(20px,1fr)_minmax(0,1400px)_minmax(20px,1fr)] grid-rows-1 aspect-[1.713] max-md:grid-cols-[16px_343px_16px] max-md:aspect-[0.394] md:max-lg:grid-cols-[16px_736px_16px] md:max-lg:aspect-[1.064]" aria-hidden="true" id="shopify-section-template--20207706636450__how-swatches-work">
        <section className="block py-20 px-12 col-span-full bg-accent max-md:px-4 md:max-lg:px-[1.92rem]">
          <div className="h-full block max-w-260 mx-auto">
            <header className="flex mb-12 flex-col items-center gap-4 text-center">
              <p className="block text-color-002 text-xs font-medium leading-[1.1875rem] tracking-[2.16px] uppercase [overflow-wrap:break-word]">
                How swatches work
              </p>
              <h2 className="block [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-[3.625rem] italic leading-[3.9375rem] tracking-[-0.86px] [overflow-wrap:break-word] max-md:text-[2rem] max-md:leading-[2.1875rem] max-md:tracking-[-0.48px] md:max-lg:text-[2.1875rem] md:max-lg:leading-[2.375rem] md:max-lg:tracking-[-0.52px]" data-component="heading">
                Three steps to clarity.
              </h2>
            </header>
            {" "}
            <ol className="border-t border-solid border-t-primary flex pt-12 flex-col gap-8 [list-style-type:none]">
              {FeatureCard_data.map((d, i) => <FeatureCard key={i} d={d} styles={FeatureCard_styles[i]} />)}
            </ol>
          </div>
          {" "}
        </section>
        {" "}
      </section>
    </>
  );
}
