import "./ditto.css";
// Generated by clone-site. Do not edit by hand.
export default function Page() {
  return (
    <>
      <section className="grid relative grid-cols-[minmax(20px,1fr)_minmax(0,1400px)_minmax(20px,1fr)] max-md:grid-cols-[16px_343px_16px] md:max-lg:grid-cols-[16px_736px_16px]" data-ditto-id="style-shopify-section-template-20207705292962-main" aria-hidden="true" id="shopify-section-template--20207706341538__hero">
        <section className="min-h-184 flex relative isolate items-end col-span-full overflow-hidden text-background max-md:min-h-[43.1375rem] md:max-lg:min-h-[54.4rem]" style={{ backgroundImage: "linear-gradient(var(--clr-1) 0%, var(--clr-2) 100%)" }}>
          <img className="w-full h-full block absolute top-0 left-0 -z-2 min-w-0 max-w-full overflow-clip object-cover aspect-[auto_2400/1600]" data-component="image" alt="The Everhem Experience" height="1600" src="/assets/cloned/images/cb3f59bc9ccc.png" width="2400" />
          {" "}
          <div className="h-full block absolute top-0 inset-x-0 -z-1 min-w-0" style={{ backgroundImage: "linear-gradient(to top, var(--clr-3), var(--clr-4) 60%, var(--clr-4) 100%)" }} />
          <div className="block relative z-1 max-w-168 p-12 max-lg:py-8 max-lg:px-4">
            <h1 className="block mb-2 [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-[4rem] font-light italic leading-[4.1875rem] tracking-[-0.64px] [overflow-wrap:break-word] max-md:text-[2.5rem] max-md:leading-10.5 max-md:tracking-[-0.4px] md:max-lg:text-[2.875rem] md:max-lg:leading-[3rem] md:max-lg:tracking-[-0.46px]" data-component="heading">
              The Everhem Experience
            </h1>
            <p className="w-full max-w-128 block mb-5 text-color-018 text-sm font-light leading-[1.375rem] [overflow-wrap:break-word]">
              From first swatch to final install, see how thoughtful design comes to life.
            </p>
            <div className="flex flex-wrap gap-2">
              <a className="border border-solid border-color-002 block py-3.5 px-7 text-xs font-medium leading-[1.1875rem] tracking-[1.44px] uppercase bg-color-002 cursor-pointer" data-component="link" href="/pages/samples">
                {"\n          Start with free swatches\n        "}
              </a>
              <a className="border border-solid border-surface block py-3.5 px-7 text-xs font-medium leading-[1.1875rem] tracking-[1.44px] uppercase cursor-pointer" data-component="link" href="https://form.typeform.com/to/HtgnBwcl">
                {"\n          Book Design Services\n        "}
              </a>
            </div>
            {" "}
          </div>
          {" "}
        </section>
        {" "}
      </section>
      <section className="grid relative grid-cols-[minmax(20px,1fr)_minmax(0,1400px)_minmax(20px,1fr)] max-md:grid-cols-[16px_343px_16px] md:max-lg:grid-cols-[16px_736px_16px]" aria-hidden="true" id="shopify-section-template--20207706341538__step-design">
        <section className="block py-16 col-span-full bg-accent max-lg:py-10">
          <div className="h-full grid max-w-350 px-8 items-start gap-16 grid-cols-[1fr_1.4fr] max-md:px-4 max-lg:gap-8 max-lg:grid-cols-1 md:max-lg:px-6" data-ditto-id="style-link-6">
            <div className="block order-[2] overflow-hidden bg-accent aspect-[0.8] max-lg:order-[1]" data-ditto-id="style-link-7">
              <img className="w-full h-210 block max-w-full overflow-clip object-cover aspect-[auto_1200/1500] max-md:h-[26.8125rem] md:max-lg:h-225.5" data-component="image" alt="01 - Design" height="1500" src="/assets/cloned/images/2e19f9018410.png" width="1200" />
            </div>
            {" "}
            <div className="flex flex-col items-start order-[1] gap-4 text-left max-lg:order-[2]">
              <p className="block text-color-002 text-xs font-medium leading-[1.1875rem] tracking-[2.16px] uppercase [overflow-wrap:break-word]">
                Overview
              </p>
              <h2 className="block [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-[2.375rem] leading-[2.625rem] tracking-[-0.19px] [overflow-wrap:break-word] max-lg:text-[1.75rem] max-lg:leading-[1.9375rem] max-lg:tracking-[-0.14px]" data-component="heading">
                01 - Design
              </h2>
              <div className="block text-color-007 font-light leading-[1.625rem]">
                <p className="block mb-4 [overflow-wrap:break-word]">
                  Everhem is here to enhance your custom window treatment experience. We've meticulously curated the best options so you can only make good choices.
                </p>
                <p className="block mb-4 [overflow-wrap:break-word]" data-ditto-id="style-button">
                  Still want help from a human? We offer virtual consultations with our design experts to ensure you effortlessly create a space that feels like home.
                </p>
                <p className="block [overflow-wrap:break-word]" data-ditto-id="style-button-2">
                  <em className="inline italic">
                    Why design alone when you can design with Everhem?
                  </em>
                </p>
              </div>
              <a className="h-12 border border-solid border-foreground flex mt-2 py-3.5 px-7 justify-center items-center text-xs font-medium leading-[1.1875rem] tracking-[2.16px] uppercase cursor-pointer" data-component="button" href="https://form.typeform.com/to/HtgnBwcl">
                {"\n          Schedule design services\n        "}
              </a>
            </div>
            {" "}
          </div>
          {" "}
        </section>
        {" "}
      </section>
      <section className="grid relative grid-cols-[minmax(20px,1fr)_minmax(0,1400px)_minmax(20px,1fr)] max-md:grid-cols-[16px_343px_16px] md:max-lg:grid-cols-[16px_736px_16px]" aria-hidden="true" id="shopify-section-template--20207706341538__step-measure">
        <section className="block py-16 col-span-full bg-accent max-lg:py-10">
          <div className="h-full grid max-w-350 px-8 items-start gap-16 grid-cols-[1fr_1.4fr] max-md:px-4 max-lg:gap-8 max-lg:grid-cols-1 md:max-lg:px-6">
            <div className="block overflow-hidden bg-accent aspect-[0.8] max-lg:order-[1]">
              <img className="w-full h-150 block max-w-full overflow-clip object-cover aspect-[auto_1200/1500] max-md:h-[26.8125rem] md:max-lg:h-225.5" data-ditto-id="style-div-2" data-component="image" alt="02 - Measure" height="1500" src="/assets/cloned/images/5e16fbdbae58.jpg" width="1200" />
            </div>
            {" "}
            <div className="flex flex-col items-start gap-4 text-left max-lg:order-[2]">
              <p className="block text-color-002 text-xs font-medium leading-[1.1875rem] tracking-[2.16px] uppercase [overflow-wrap:break-word]" data-ditto-id="style-div-3">
                Overview
              </p>
              <h2 className="block [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-[2.375rem] leading-[2.625rem] tracking-[-0.19px] [overflow-wrap:break-word] max-lg:text-[1.75rem] max-lg:leading-[1.9375rem] max-lg:tracking-[-0.14px]" data-component="heading">
                02 - Measure
              </h2>
              <div className="block text-color-007 font-light leading-[1.625rem]" data-ditto-id="style-div-4">
                <p className="block mb-4 [overflow-wrap:break-word]">
                  If you can use a tape measure, you can confidently order custom window treatments with ease.
                </p>
                <p className="block mb-4 [overflow-wrap:break-word]" data-ditto-id="style-shopify-section-template-20207706308770-tabs">
                  We guide you through each measurement step, providing our expert opinion along the way, ensuring you will customize perfect fitting window treatments for your space.
                </p>
                <p className="block [overflow-wrap:break-word]">
                  <strong className="inline font-normal" data-ditto-id="style-div-5">
                    Need more than virtual help?
                  </strong>
                  {" Onsite measuring services are available in select cities - contact us to explore your options."}
                </p>
              </div>
              <a className="h-12 border border-solid border-foreground flex mt-2 py-3.5 px-7 justify-center items-center text-xs font-medium leading-[1.1875rem] tracking-[2.16px] uppercase cursor-pointer" data-component="button" href="/pages/guidance">
                {"\n          Learn to measure\n        "}
              </a>
            </div>
            {" "}
          </div>
          {" "}
        </section>
        {" "}
      </section>
      <section className="grid relative grid-cols-[minmax(20px,1fr)_minmax(0,1400px)_minmax(20px,1fr)] grid-rows-1 aspect-[4/3] max-md:grid-cols-[16px_343px_16px] max-md:aspect-[0.419] md:max-lg:grid-cols-[16px_736px_16px] md:max-lg:aspect-[0.596]" data-ditto-id="style-div-6" aria-hidden="true" id="shopify-section-template--20207706341538__step-order">
        <section className="block py-16 col-span-full bg-accent max-lg:py-10">
          <div className="h-full grid max-w-350 px-8 items-start gap-16 grid-cols-[1fr_1.4fr] max-md:px-4 max-lg:gap-8 max-lg:grid-cols-1 md:max-lg:px-6">
            <div className="block order-[2] overflow-hidden bg-accent aspect-[0.8] max-lg:order-[1]">
              <img className="w-full h-210 block max-w-full overflow-clip object-cover aspect-[auto_1200/1500] max-md:h-[26.8125rem] md:max-lg:h-225.5" data-component="image" alt="03 - Order" height="1500" src="/assets/cloned/images/e882882c380f.jpg" width="1200" />
            </div>
            {" "}
            <div className="flex flex-col items-start order-[1] gap-4 text-left max-lg:order-[2]" data-ditto-id="style-p">
              <p className="block text-color-002 text-xs font-medium leading-[1.1875rem] tracking-[2.16px] uppercase [overflow-wrap:break-word]">
                Overview
              </p>
              <h2 className="block [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-[2.375rem] leading-[2.625rem] tracking-[-0.19px] [overflow-wrap:break-word] max-lg:text-[1.75rem] max-lg:leading-[1.9375rem] max-lg:tracking-[-0.14px]" data-ditto-id="style-div-7" data-component="heading">
                03 - Order
              </h2>
              <div className="block text-color-007 font-light leading-[1.625rem]">
                <p className="block mb-4 [overflow-wrap:break-word]" data-ditto-id="style-div-8">
                  Our seamless online interface simplifies the process of ordering window treatments tailored to your space.
                </p>
                <p className="block [overflow-wrap:break-word]">
                  Our step-by-step guidance walks you through each decision, reducing complexity and making it a memorable, design-driven experience.
                </p>
              </div>
              <a className="h-12 border border-solid border-foreground flex mt-2 py-3.5 px-7 justify-center items-center text-xs font-medium leading-[1.1875rem] tracking-[2.16px] uppercase cursor-pointer" data-ditto-id="style-shades-guide-top" data-component="button" href="/pages/shop">
                {"\n          Shop now\n        "}
              </a>
            </div>
            {" "}
          </div>
          {" "}
        </section>
        {" "}
      </section>
      <section className="grid relative grid-cols-[minmax(20px,1fr)_minmax(0,1400px)_minmax(20px,1fr)] max-md:grid-cols-[16px_343px_16px] md:max-lg:grid-cols-[16px_736px_16px]" aria-hidden="true" id="shopify-section-template--20207706341538__step-install">
        <section className="block py-16 col-span-full bg-accent max-lg:py-10">
          <div className="h-full grid max-w-350 px-8 items-start gap-16 grid-cols-[1fr_1.4fr] max-md:px-4 max-lg:gap-8 max-lg:grid-cols-1 md:max-lg:px-6">
            <div className="block overflow-hidden bg-accent aspect-[0.8] max-lg:order-[1]">
              <img className="w-full h-150 block max-w-full overflow-clip object-cover aspect-[auto_1200/1500] max-md:h-[26.8125rem] md:max-lg:h-225.5" data-ditto-id="style-link-8" data-component="image" alt="04 - Install" height="1500" src="/assets/cloned/images/9afb9e7c4b15.jpg" width="1200" />
            </div>
            {" "}
            <div className="flex flex-col items-start gap-4 text-left max-lg:order-[2]">
              <p className="block text-color-002 text-xs font-medium leading-[1.1875rem] tracking-[2.16px] uppercase [overflow-wrap:break-word]" data-ditto-id="style-link-9">
                Overview
              </p>
              <h2 className="block [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-[2.375rem] leading-[2.625rem] tracking-[-0.19px] [overflow-wrap:break-word] max-lg:text-[1.75rem] max-lg:leading-[1.9375rem] max-lg:tracking-[-0.14px]" data-component="heading">
                04 - Install
              </h2>
              <div className="block text-color-007 font-light leading-[1.625rem]">
                <p className="block mb-4 [overflow-wrap:break-word]">
                  We empower you to install your custom window treatments with ease using our user-friendly approach.
                </p>
                <p className="block mb-4 [overflow-wrap:break-word]">
                  Our comprehensive guides make the installation process a seamless and collaborative experience, ensuring it feels as if we're right there with you every step of the way.
                </p>
                <p className="block [overflow-wrap:break-word]" data-ditto-id="style-link-10">
                  <strong className="inline font-normal">
                    Need more than virtual help?
                  </strong>
                  {" Onsite installation services are available in select cities - contact us to explore your options."}
                </p>
              </div>
              <a className="h-12 border border-solid border-foreground flex mt-2 py-3.5 px-7 justify-center items-center text-xs font-medium leading-[1.1875rem] tracking-[2.16px] uppercase cursor-pointer" data-ditto-id="style-link-11" data-component="button" href="/pages/guidance">
                {"\n          View install guides\n        "}
              </a>
            </div>
            {" "}
          </div>
          {" "}
        </section>
        {" "}
      </section>
      <section className="grid relative grid-cols-[minmax(20px,1fr)_minmax(0,1400px)_minmax(20px,1fr)] grid-rows-1 aspect-[4.963] max-md:grid-cols-[16px_343px_16px] max-md:aspect-[1.376] md:max-lg:grid-cols-[16px_736px_16px] md:max-lg:aspect-[3.624]" aria-hidden="true" id="shopify-section-template--20207706341538__final-cta">
        <div className="block py-11 col-start-2 bg-background max-lg:py-8">
          <div className="h-full flex max-w-208 mx-auto px-8 flex-col items-center gap-4 text-center max-md:px-4 md:max-lg:px-6">
            <p className="block text-color-002 text-xs font-medium leading-[1.1875rem] tracking-[2.16px] uppercase [overflow-wrap:break-word]">
              Ready to begin?
            </p>
            <h1 className="block max-w-full [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-[3.5rem] font-light italic leading-[3.5625rem] tracking-[-0.56px] [overflow-wrap:break-word] max-lg:text-4xl max-lg:leading-[2.3125rem] max-lg:tracking-[-0.36px]" data-component="heading">
              Let's get started.
            </h1>
            <div className="w-[61.5%] flex mt-2 flex-wrap gap-2 max-md:w-full max-md:flex-col md:max-lg:w-[68.5%]">
              <a className="h-[52.5938px] border border-solid border-foreground flex py-4 px-8 justify-center items-center text-background text-xs font-medium leading-[1.1875rem] tracking-[1.44px] uppercase bg-foreground cursor-pointer" data-ditto-id="style-subscribe" data-component="button" href="/pages/samples">
                {"\n          Order free swatches\n        "}
              </a>
              <a className="h-[52.5938px] border border-solid border-foreground flex py-4 px-8 justify-center items-center text-xs font-medium leading-[1.1875rem] tracking-[1.44px] uppercase cursor-pointer" data-component="button" href="https://form.typeform.com/to/HtgnBwcl">
                {"\n          Book a design session\n        "}
              </a>
            </div>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      <section className="grid relative grid-cols-[minmax(20px,1fr)_minmax(0,1400px)_minmax(20px,1fr)] max-md:grid-cols-[16px_343px_16px] md:max-lg:grid-cols-[16px_736px_16px]" aria-hidden="true" id="shopify-section-template--20207706341538__everhem_photo_break_BXnYqL">
        <a className="h-144 min-h-120 block relative col-span-full overflow-hidden text-background bg-accent cursor-pointer max-md:h-[487.188px] max-lg:min-h-95 md:max-lg:h-[614.391px]" data-ditto-id="style-div" data-component="link" aria-label="shop now" href="/pages/shop">
          <img className="w-full h-144 block max-w-full overflow-clip object-cover aspect-[auto_2400/1400] max-md:h-[30.4375rem] md:max-lg:h-153.5" data-component="image" alt="Everhem lifestyle" height="1400" src="/assets/cloned/images/17113821c95d.jpg" width="2400" />
          <div className="h-full block absolute top-0 inset-x-0 pointer-events-none" style={{ backgroundImage: "linear-gradient(to top, var(--clr-5), var(--clr-6) 40%, var(--clr-7) 70%)" }} data-ditto-id="style-shades-guide-shade-type" aria-hidden="true" />
          {" "}
          <div className="h-6 flex absolute bottom-16 inset-x-0 px-8 flex-col items-center gap-2 text-center max-md:bottom-8 max-md:px-4 md:max-lg:bottom-[2.4rem] md:max-lg:px-6">
            <p className="border-b border-solid border-b-color-019 flex pb-0.5 items-center gap-2.5 text-sm font-medium leading-[1.375rem] tracking-[1.68px] uppercase [overflow-wrap:break-word]" data-ditto-id="style-header">
              <span className="block">
                shop now
              </span>
              {" "}
              <svg className="w-auto h-2.5 block max-w-full overflow-hidden" data-component="icon" aria-hidden="true" fill="none" height="10" viewBox="0 0 14 10" width="14">
                <path d="M1 5h12m0 0L9 1m4 4L9 9" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round" />
              </svg>
              {" "}
            </p>
            {" "}
          </div>
          {" "}
        </a>
        {" "}
      </section>
    </>
  );
}
