import "./ditto.css";
import MediaCard from "./components/media-card";
import ListRow from "./components/list-row";
import Tile from "./components/tile";
// Generated by clone-site. Do not edit by hand.
const MediaCard_data = [
    { alt: "Your Partner in Design", imgSrc: "/assets/cloned/images/ef212e1057ec.webp", text: "01", title: "Your Partner in Design", description: "Founded by an interior designer, Everhem was built with a deep understanding of the design process. We partner with designers to deliver beautiful, custom window treatments with confidence and ease." },
    { alt: "Dedicated Project Support", imgSrc: "/assets/cloned/images/561365ca15e6.jpg", text: "02", title: "Dedicated Project Support", description: "Our team manages the details, from measuring and specifications to production and installation, providing clear communication and organized project management every step of the way." },
    { alt: "Fully Custom", imgSrc: "/assets/cloned/images/df2d4318cd8f.jpg", text: "03", title: "Fully Custom", description: "Access our full custom workroom capabilities to create bespoke window treatment solutions tailored to your project's exact vision and requirements." }
];
const ListRow_data = [
    { text: "15% trade discount, year round" },
    { text: "Dedicated account manager for full project support" },
    { text: "COM capabilities" },
    { text: "Full custom workroom capabilities" },
    { text: "Unlimited free swatces" },
    { text: "Tax-exempt account setup with a valid resale license" }
];
const Tile_data = [
    { text: "What is your Trade discount?", description: "Our Trade discount is 15% year round regardless of order size or volume. Once you have an active trade account, this discount is automatically applied to any order in your cart so long as you're logged in." },
    { text: "Who qualifies to join your Trade program?", description: "Our Trade program is available to design professionals for their respective services and projects. In order to qualify, you must verify your business with the proper credentials during the application process. We do not offer Trade approval for retail or e-commerce businesses who are interested in wholesaling our products." },
    { text: "What credentials do I need to apply?", description: "You will need to upload a valid Business License, EIN or Resale Certificate in order for your application to be approved. We do not require membership in a major design organization (e.g. ASID) but if you belong to one you are encouraged to upload your membership ID." }
];
const MediaCard_meta: string[][] = [
    ["style-div-2", "n61", "style-div-3", "n63", "style-div-4", "n65", "style-shopify-section-template-20207706308770-tabs", "n67"],
    ["style-div-5", "n69", "style-div-6", "n71", "n72", "n73", "n74", "style-p"],
    ["n76", "style-div-7", "n78", "style-div-8", "n80", "style-shades-guide-top", "n82", "n83"]
];
const ListRow_meta: string[][] = [
    ["n92"],
    ["style-link-10"],
    ["n94"],
    ["style-link-11"],
    ["n96"],
    ["n97"]
];
const Tile_meta: string[][] = [
    ["n108", "style-header", "n110", "n111", "n112", "n113"],
    ["n114", "n115", "n116", "n117", "n118", "n119"],
    ["n120", "n121", "n122", "n123", "n124", "n125"]
];
const ListRow_styles = [
    {  },
    {  },
    {  },
    {  },
    {  },
    { className: "border-b border-b-primary" }
];

export default function Page() {
  return (
    <>
      <section className="grid relative grid-cols-[minmax(20px,1fr)_minmax(0,1400px)_minmax(20px,1fr)] max-md:grid-cols-[16px_343px_16px] md:max-lg:grid-cols-[16px_736px_16px]" data-ditto-id="style-shopify-section-template-20207705292962-main" aria-hidden="true" id="shopify-section-template--20207706833058__hero">
        <section className="min-h-184 flex relative isolate items-end col-span-full overflow-hidden text-background max-md:min-h-[43.1375rem] md:max-lg:min-h-[54.4rem]" style={{ backgroundImage: "linear-gradient(var(--clr-1) 0%, var(--clr-2) 100%)" }}>
          <img className="w-full h-full block absolute top-0 left-0 -z-2 min-w-0 max-w-full overflow-clip object-cover aspect-[auto_2400/1600]" data-component="image" alt="For Designers, By Designers." height="1600" src="/assets/cloned/images/32990f09f92d.jpg" width="2400" />
          {" "}
          <div className="h-full block absolute top-0 inset-x-0 -z-1 min-w-0" style={{ backgroundImage: "linear-gradient(to top, var(--clr-3), var(--clr-4) 60%, var(--clr-4) 100%)" }} />
          <div className="block relative z-1 max-w-168 p-12 max-lg:py-8 max-lg:px-4">
            <h1 className="block mb-2 [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-[4rem] font-light italic leading-[4.1875rem] tracking-[-0.64px] [overflow-wrap:break-word] max-md:text-[2.5rem] max-md:leading-10.5 max-md:tracking-[-0.4px] md:max-lg:text-[2.875rem] md:max-lg:leading-[3rem] md:max-lg:tracking-[-0.46px]" data-component="heading">
              For Designers, By Designers.
            </h1>
            <p className="w-full max-w-128 block mb-5 text-color-018 text-sm font-light leading-[1.375rem] [overflow-wrap:break-word]">
              Trade pricing, dedicated support and full custom capabilities.
            </p>
            <div className="flex flex-wrap gap-2">
              <a className="border border-solid border-color-002 block py-3.5 px-7 text-xs font-medium leading-[1.1875rem] tracking-[1.44px] uppercase bg-color-002 cursor-pointer" data-component="link" href="https://form.typeform.com/to/Q4zU4Oyf?typeform-source=www.everhem.com">
                {"\n          Apply to join\n        "}
              </a>
            </div>
            {" "}
          </div>
          {" "}
        </section>
        {" "}
      </section>
      <section className="grid relative grid-cols-[minmax(20px,1fr)_minmax(0,1400px)_minmax(20px,1fr)] max-md:grid-cols-[16px_343px_16px] md:max-lg:grid-cols-[16px_736px_16px]" aria-hidden="true" id="shopify-section-template--20207706833058__intro">
        <section className="block py-16 col-span-full bg-accent max-lg:py-10">
          <div className="h-full grid max-w-350 px-8 items-start gap-16 grid-cols-[1fr_1.4fr] max-md:px-4 max-lg:gap-8 max-lg:grid-cols-1 md:max-lg:px-6">
            <div className="block overflow-hidden bg-accent aspect-[0.8] max-lg:order-[1]" data-ditto-id="style-link-6">
              <img className="w-full h-150 block max-w-full overflow-clip object-cover aspect-[auto_1200/1500] max-md:h-[26.8125rem] md:max-lg:h-225.5" data-ditto-id="style-link-7" data-component="image" alt="A better window treatment experience for designers." height="1500" src="/assets/cloned/images/c55a28061202.jpg" width="1200" />
            </div>
            {" "}
            <div className="flex p-12 flex-col items-start gap-4 text-left bg-accent max-md:p-7 max-lg:order-[2] md:max-lg:p-[1.92rem]">
              <p className="block text-color-002 text-xs font-medium leading-[1.1875rem] tracking-[2.16px] uppercase [overflow-wrap:break-word]">
                Your Partner in Design
              </p>
              <h2 className="block [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-[2.375rem] leading-[2.625rem] tracking-[-0.19px] [overflow-wrap:break-word] max-lg:text-[1.75rem] max-lg:leading-[1.9375rem] max-lg:tracking-[-0.14px]" data-component="heading">
                A better window treatment experience for designers.
              </h2>
              <div className="block text-color-007 font-light leading-[1.625rem]">
                <p className="block mb-4 [overflow-wrap:break-word]">
                  Everhem's Trade Program welcomes designers, decorators, and architects from all backgrounds. Enjoy competitive trade pricing with a 15% discount, alongside exclusive services tailored for trade members - including custom capabilities, dedicated support, and priority access.
                </p>
                <p className="block [overflow-wrap:break-word]">
                  To get started, fill out the application below. You can expect a confirmation email within 24-48 hours.
                </p>
              </div>
              <a className="h-12 border border-solid border-foreground flex mt-2 py-3.5 px-7 justify-center items-center text-xs font-medium leading-[1.1875rem] tracking-[2.16px] uppercase cursor-pointer" data-ditto-id="style-button" data-component="button" href="https://form.typeform.com/to/Q4zU4Oyf?typeform-source=www.everhem.com">
                {"\n          Apply to the program\n        "}
              </a>
            </div>
            {" "}
          </div>
          {" "}
        </section>
        {" "}
      </section>
      <section className="grid relative grid-cols-[minmax(20px,1fr)_minmax(0,1400px)_minmax(20px,1fr)] grid-rows-1 aspect-[1.383] max-md:grid-cols-[16px_343px_16px] max-md:aspect-[0.241] md:max-lg:grid-cols-[16px_736px_16px] md:max-lg:aspect-[0.346]" data-ditto-id="style-button-2" aria-hidden="true" id="shopify-section-template--20207706833058__principles">
        <section className="block py-11 col-span-full bg-accent max-lg:py-8">
          <div className="h-full block max-w-350 px-8 max-md:px-4 md:max-lg:px-6">
            <div className="flex max-w-176 mb-16 mx-auto flex-col gap-4 text-center max-lg:mb-10">
              <h2 className="block [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-[2.8125rem] leading-[3.0625rem] tracking-[-0.22px] [overflow-wrap:break-word] max-lg:text-3xl max-lg:leading-[2.0625rem] max-lg:tracking-[-0.15px]" data-component="heading">
                For the Trade, By Design
              </h2>
              <p className="block max-w-152 mx-auto text-color-011 font-light leading-[1.625rem] [overflow-wrap:break-word]">
                We believe good design is the foundation of a good home. Here's what goes into every window treatment we make.
              </p>
            </div>
            <div className="grid gap-[3.2rem] grid-cols-3 max-lg:gap-12 max-lg:grid-cols-1">
              {MediaCard_data.map((d, i) => <MediaCard key={i} d={d} />)}
            </div>
          </div>
          {" "}
        </section>
        {" "}
      </section>
      <section className="grid relative grid-cols-[minmax(20px,1fr)_minmax(0,1400px)_minmax(20px,1fr)] max-md:grid-cols-[16px_343px_16px] md:max-lg:grid-cols-[16px_736px_16px]" aria-hidden="true" id="shopify-section-template--20207706833058__benefits">
        <section className="block py-16 col-span-full bg-accent max-lg:py-10">
          <div className="h-full grid max-w-350 px-8 items-center gap-16 grid-cols-2 max-md:px-4 max-lg:gap-8 max-lg:grid-cols-1 md:max-lg:px-6" data-ditto-id="style-link-8">
            <div className="block overflow-hidden bg-background aspect-[0.8]">
              <img className="w-full h-180 block max-w-full overflow-clip object-cover aspect-[auto_1200/1500] max-md:h-[26.8125rem] md:max-lg:h-225.5" data-ditto-id="style-link-9" data-component="image" alt="Everything you need, on every project." height="1500" src="/assets/cloned/images/b8f428e72f4e.jpg" width="1200" />
              {" "}
            </div>
            <div className="flex flex-col">
              <h2 className="block mb-4.5 [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-[2.75rem] italic leading-[3.1875rem] [overflow-wrap:break-word] max-lg:text-[1.75rem] max-lg:leading-[2rem]" data-component="heading">
                Everything you need, on every project.
              </h2>
              <ul className="block mb-8 [list-style-type:none] max-lg:mb-6">
                {ListRow_data.map((d, i) => <ListRow key={i} d={d} styles={ListRow_styles[i]} />)}
              </ul>
              <a className="border border-solid border-foreground block py-3.5 px-7 self-start text-accent text-sm leading-[1.375rem] tracking-[0.56px] uppercase bg-foreground cursor-pointer" data-component="link" href="https://form.typeform.com/to/Q4zU4Oyf?typeform-source=www.everhem.com">
                Apply to join
              </a>
            </div>
            {" "}
          </div>
          {" "}
        </section>
        {" "}
      </section>
      <section className="grid relative grid-cols-[minmax(20px,1fr)_minmax(0,1400px)_minmax(20px,1fr)] grid-rows-1 aspect-[1.38] max-md:grid-cols-[16px_343px_16px] max-md:aspect-[0.441] md:max-lg:grid-cols-[16px_736px_16px] md:max-lg:aspect-square" aria-hidden="true" id="shopify-section-template--20207706833058__faqs">
        <section className="block py-16 col-span-full bg-background max-lg:py-10">
          <div className="h-full block max-w-215 mx-auto px-8 max-md:px-4 md:max-lg:px-6">
            <div className="block mb-11 text-center max-lg:mb-7" data-ditto-id="style-subscribe">
              <h1 className="block mb-3.5 [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-5xl italic leading-[3.3125rem] [overflow-wrap:break-word] max-lg:text-[2rem] max-lg:leading-[2.1875rem]" data-component="heading">
                Trade FAQs
              </h1>
              <p className="block max-w-150 mx-auto text-color-011 leading-6 [overflow-wrap:break-word]">
                Quick answers for the questions we get most.
              </p>
            </div>
            <div className="block" data-ditto-id="style-div" id="faq-all-template--20207706833058__faqs">
              <div className="block mb-12 max-lg:mb-8" id="faq-cat-template--20207706833058__faqs-trade">
                <h2 className="border-b border-solid border-b-primary block mb-4 pb-2.5 [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-2xl leading-[1.8125rem] [overflow-wrap:break-word] max-lg:text-xl max-lg:leading-6" data-ditto-id="style-shades-guide-shade-type" data-component="heading">
                  Trade
                </h2>
                {Tile_data.map((d, i) => <Tile key={i} d={d} />)}
                <details className="border-b border-solid border-b-primary block">
                  <summary className="flex py-4.5 px-1 justify-between items-center gap-4 cursor-pointer">
                    <span className="block grow basis-0">
                      Do you work with COM?
                    </span>
                    {" "}
                    <span className="w-3.5 h-3.5 block relative shrink-0 before:content-[''] before:block before:absolute before:top-1.5 before:bottom-1.5 before:inset-x-0 before:w-3.5 before:h-px before:bg-clr-1 before:transform-[matrix(1,0,0,1,0,-0.5)] before:origin-[7px_0.5px] 2xl:before:hidden after:content-[''] after:block after:absolute after:inset-y-0 after:right-1.5 after:left-1.5 after:w-px after:h-3.5 after:bg-clr-1 after:transform-[matrix(1,0,0,1,-0.5,0)] after:origin-[0.5px_7px] 2xl:after:hidden" aria-hidden="true" />
                    {" "}
                  </summary>
                  {" "}
                  <div className="block pb-5.5 px-1 text-color-005 leading-[1.625rem]">
                    <p className="block [overflow-wrap:break-word]">
                      {"We will absolutely work with COM. Please contact your dedicated "}
                      <a className="inline text-foreground underline cursor-pointer" data-component="link" href="mailto:trade@everhem.com">
                        Trade Specialist
                      </a>
                      {" for next steps. We work with you on yardage calculations - you're responsible for ordering the material and shipping it to us. Because COM fabrics may grow, we cannot warranty COM work against expansion."}
                    </p>
                  </div>
                  {" "}
                </details>
                <details className="border-b border-solid border-b-primary block">
                  <summary className="flex py-4.5 px-1 justify-between items-center gap-4 cursor-pointer">
                    <span className="block grow basis-0">
                      Does your Trade program offer tax exemption?
                    </span>
                    {" "}
                    <span className="w-3.5 h-3.5 block relative shrink-0 before:content-[''] before:block before:absolute before:top-1.5 before:bottom-1.5 before:inset-x-0 before:w-3.5 before:h-px before:bg-clr-1 before:transform-[matrix(1,0,0,1,0,-0.5)] before:origin-[7px_0.5px] 2xl:before:hidden after:content-[''] after:block after:absolute after:inset-y-0 after:right-1.5 after:left-1.5 after:w-px after:h-3.5 after:bg-clr-1 after:transform-[matrix(1,0,0,1,-0.5,0)] after:origin-[0.5px_7px] 2xl:after:hidden" aria-hidden="true" />
                    {" "}
                  </summary>
                  {" "}
                  <div className="block pb-5.5 px-1 text-color-005 leading-[1.625rem]">
                    <p className="block [overflow-wrap:break-word]">
                      {"Sales tax is applied in select states. If you hold a valid resale license, you can be set up as tax-exempt. Upload your resale license during the application, or email it to "}
                      <a className="inline text-foreground underline cursor-pointer" data-component="link" href="mailto:trade@everhem.com">
                        trade@everhem.com
                      </a>
                      {" if you're already a member."}
                    </p>
                  </div>
                  {" "}
                </details>
              </div>
              {" "}
            </div>
            <div className="block mt-16 py-12 px-[2.4rem] text-center bg-accent max-lg:mt-10 max-lg:py-8 max-lg:px-6">
              <h3 className="block mb-2.5 [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-[1.75rem] italic leading-[2.125rem] [overflow-wrap:break-word] max-lg:text-xl max-lg:leading-6" data-component="heading">
                Didn't find what you're looking for?
              </h3>
              <p className="block mb-5 text-color-003 [overflow-wrap:break-word]">
                Browse the full FAQ or reach out to our trade team.
              </p>
              <a className="border border-solid border-foreground inline-block py-3.5 px-7 text-accent text-sm leading-[1.375rem] tracking-[0.56px] uppercase bg-foreground cursor-pointer" data-component="button" href="/pages/faq">
                View all FAQs
              </a>
            </div>
          </div>
          {" "}
        </section>
        {"  "}
      </section>
      <section className="grid relative grid-cols-[minmax(20px,1fr)_minmax(0,1400px)_minmax(20px,1fr)] grid-rows-1 aspect-[4.285] max-md:grid-cols-[16px_343px_16px] max-md:aspect-[1.193] md:max-lg:grid-cols-[16px_736px_16px] md:max-lg:aspect-[3.039]" aria-hidden="true" id="shopify-section-template--20207706833058__ready-cta">
        <div className="block py-11 col-start-2 bg-background max-lg:py-8">
          <div className="h-full flex max-w-208 mx-auto px-8 flex-col items-center gap-4 text-center max-md:px-4 md:max-lg:px-6">
            <p className="block text-color-002 text-xs font-medium leading-[1.1875rem] tracking-[2.16px] uppercase [overflow-wrap:break-word]">
              Ready to get started?
            </p>
            <h1 className="block max-w-full [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-[3.5rem] font-light italic leading-[3.5625rem] tracking-[-0.56px] [overflow-wrap:break-word] max-lg:text-4xl max-lg:leading-[2.3125rem] max-lg:tracking-[-0.36px]" data-component="heading">
              Apply to join Everhem Trade
            </h1>
            <div className="block max-w-full text-color-003">
              <p className="block [overflow-wrap:break-word]">
                {"Approval typically takes 1-2 business days. "}
              </p>
            </div>
            <div className="w-36 flex mt-2 flex-wrap gap-2 max-md:w-[19.4375rem] max-md:flex-col">
              <a className="h-[52.5938px] border border-solid border-foreground flex py-4 px-8 justify-center items-center text-background text-xs font-medium leading-[1.1875rem] tracking-[1.44px] uppercase bg-foreground cursor-pointer" data-component="button" href="#trade-application">
                {"\n          Apply now\n        "}
              </a>
            </div>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
    </>
  );
}
