import "./ditto.css";
import CardLink from "./components/card-link";
import Tile from "./components/tile";
import ListRow from "./components/list-row";
import MediaCard from "./components/media-card";
import MediaTile from "./components/media-tile";
import MediaTile2 from "./components/media-tile2";
import MediaCard2 from "./components/media-card2";
import MediaCard3 from "./components/media-card3";
import MediaCard4 from "./components/media-card4";
// Generated by clone-site. Do not edit by hand.
const CardLink_data = [
    { href: "/pages/samples", alt: "Order Swatches", imgSrc: "/assets/cloned/images/3b267e6b7541.png", title: "Order Swatches", description: "Feel the fabrics before you buy.", label: "\n                  Shop Now\n                  " },
    { href: "https://form.typeform.com/to/HtgnBwcl", alt: "Design Services", imgSrc: "/assets/cloned/images/6a78979e4a25.jpg", title: "Design Services", description: "Get expert guidance for your windows.", label: "\n                  Book Now\n                  " },
    { href: "#", alt: "Measure Your Windows", imgSrc: "/assets/cloned/images/ca6531837616.jpg", title: "Measure Your Windows", description: "Precision at every step with our simple guides.", label: "\n                  Start Here\n                  " }
];
const Tile_data = [
    { ariaselected: "true", label: "\n          Shades\n        " },
    { ariaselected: "false", label: "\n          Drapery\n        " },
    { ariaselected: "false", label: "\n          Café Curtains\n        " },
    { ariaselected: "false", label: "\n          Fixed Curtains\n        " },
    { ariaselected: "false", label: "\n          Hardware\n        " },
    { ariaselected: "false", label: "\n          Measure & Install\n        " }
];
const ListRow_data = [
    { href: "#shades-guide-shade-type", label: "Shade Type" },
    { href: "#shades-guide-fabric", label: "Fabric" },
    { href: "#shades-guide-lining", label: "Lining" },
    { href: "#shades-guide-mount", label: "Mount" },
    { href: "#shades-guide-control", label: "Control" },
    { href: "#shades-guide-operation", label: "Operation" },
    { href: "#shades-guide-measure", label: "Measure" }
];
const MediaCard_data = [
    { alt: "Flat Roman shade — lifestyle", imgSrc: "/assets/cloned/images/2528be2c8478.jpg", title: "Flat Roman", description: "Clean, architectural lines. Lies flat when lowered for a tailored, modern look." },
    { alt: "Pleated Roman shade — lifestyle", imgSrc: "/assets/cloned/images/fc1deb9d4531.jpg", title: "Pleated Roman", description: "Structured horizontal folds that stack evenly when raised — classic and considered." },
    { alt: "Relaxed Roman shade — lifestyle", imgSrc: "/assets/cloned/images/1044c69fd4fa.jpg", title: "Relaxed Roman", description: "A soft smile at the hem. Effortless, slightly romantic, and unlined by nature." },
    { alt: "London Roman shade — lifestyle", imgSrc: "/assets/cloned/images/f598ea074d2a.jpg", title: "London Roman", description: "Two soft gathers create subtle drape at the sides — traditional with quiet personality." },
    { alt: "Woven Wood shade — lifestyle", imgSrc: "/assets/cloned/images/cc768194f920.jpg", title: "Woven Wood", description: "Natural grasses, reeds, and bamboo. Textural warmth and filtered, golden light." },
    { alt: "Roller shade — lifestyle", imgSrc: "/assets/cloned/images/44c4149385a1.jpg", title: "Roller", description: "Minimal profile, maximal utility. A smooth wrap around a slim tube — ideal anywhere." }
];
const MediaTile_data = [
    { alt: "Quartz — Everhem Hues", imgSrc: "/assets/cloned/images/e4cc20883ab8.png", description: "Quartz" },
    { alt: "Driftwood — Everhem Hues", imgSrc: "/assets/cloned/images/ceaad9a29aa3.png", description: "Driftwood" },
    { alt: "Flax — Everhem Hues", imgSrc: "/assets/cloned/images/db8c4cbc70b1.png", description: "Flax" },
    { alt: "Granite — Everhem Hues", imgSrc: "/assets/cloned/images/766c7e76ed35.png", description: "Granite" },
    { alt: "Umber — Everhem Hues", imgSrc: "/assets/cloned/images/c8d2a872ddae.png", description: "Umber" },
    { alt: "Cognac — Everhem Hues", imgSrc: "/assets/cloned/images/3b3dbbb95273.png", description: "Cognac" },
    { alt: "Juniper — Everhem Hues", imgSrc: "/assets/cloned/images/626c32aecfa4.png", description: "Juniper" }
];
const MediaTile_data2 = [
    { alt: "Moon — Everhem Essentials", imgSrc: "/assets/cloned/images/2ffd079d3e22.jpg", description: "Moon" },
    { alt: "Bone — Everhem Essentials", imgSrc: "/assets/cloned/images/442a07eafb1b.jpg", description: "Bone" },
    { alt: "Sand — Everhem Essentials", imgSrc: "/assets/cloned/images/d894ad93f9fd.jpg", description: "Sand" },
    { alt: "Birch — Everhem Essentials", imgSrc: "/assets/cloned/images/b531d43f2032.jpg", description: "Birch" },
    { alt: "Ash — Everhem Essentials", imgSrc: "/assets/cloned/images/0fd5dd2b1770.jpg", description: "Ash" },
    { alt: "Sage — Everhem Essentials", imgSrc: "/assets/cloned/images/880342cd189d.jpg", description: "Sage" },
    { alt: "Rose — Everhem Essentials", imgSrc: "/assets/cloned/images/6aec8958fd94.jpg", description: "Rose" }
];
const MediaTile2_data = [
    { alt: "Haze — Jake Arnold for Everhem", imgSrc: "/assets/cloned/images/4b85bb2a3fac.jpg", description: "Haze" },
    { alt: "Saffron — Jake Arnold for Everhem", imgSrc: "/assets/cloned/images/93130b979221.jpg", description: "Saffron" },
    { alt: "Diamond Magnolia — Jake Arnold for Everhem", imgSrc: "/assets/cloned/images/35faf96c9614.jpg", description: "Diamond Magnolia" },
    { alt: "Parchment Magnolia — Jake Arnold for Everhem", imgSrc: "/assets/cloned/images/f46773a0fe6e.jpg", description: "Parchment Magnolia" },
    { alt: "Gardenia — Jake Arnold for Everhem", imgSrc: "/assets/cloned/images/2048cc8496c4.jpg", description: "Gardenia" },
    { alt: "Limestone — Jake Arnold for Everhem", imgSrc: "/assets/cloned/images/571d84e41510.jpg", description: "Limestone" },
    { alt: "Mist — Jake Arnold for Everhem", imgSrc: "/assets/cloned/images/593d46f5a465.png", description: "Mist" },
    { alt: "Citrine — Jake Arnold for Everhem", imgSrc: "/assets/cloned/images/8043d3620e1e.jpg", description: "Citrine" },
    { alt: "Magnolia Sheer — Jake Arnold for Everhem", imgSrc: "/assets/cloned/images/9810f15a64aa.jpg", description: "Magnolia Sheer" },
    { alt: "Parchment Sheer — Jake Arnold for Everhem", imgSrc: "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7", description: "Parchment Sheer" },
    { alt: "Parlor Stripe Sheer — Jake Arnold for Everhem", imgSrc: "/assets/cloned/images/53a388e97870.jpg", description: "Parlor Stripe Sheer" },
    { alt: "Sudare Kurumi — Jake Arnold for Everhem", imgSrc: "/assets/cloned/images/df5259b56577.jpg", description: "Sudare Kurumi" },
    { alt: "Lotus Trim — Jake Arnold for Everhem", imgSrc: "/assets/cloned/images/2c65819f87c7.jpg", description: "Lotus Trim" },
    { alt: "Medallion Trim — Jake Arnold for Everhem", imgSrc: "/assets/cloned/images/3fe2bf036ef3.jpg", description: "Medallion Trim" },
    { alt: "Willow Trim — Jake Arnold for Everhem", imgSrc: "/assets/cloned/images/03bbe14952e0.jpg", description: "Willow Trim" }
];
const MediaTile_data3 = [
    { alt: "Moon Sheer", imgSrc: "/assets/cloned/images/89ba73fd7283.jpg", description: "Moon Sheer" },
    { alt: "Bone Sheer", imgSrc: "/assets/cloned/images/b7f7244b26ee.jpg", description: "Bone Sheer" },
    { alt: "Pebble Sheer", imgSrc: "/assets/cloned/images/dd29087fec58.jpg", description: "Pebble Sheer" }
];
const MediaTile_data4 = [
    { alt: "Starry Moons — Carly Kuhn Collection", imgSrc: "/assets/cloned/images/268f57a72242.jpg", description: "Starry Moons" },
    { alt: "Winking Diamonds — Carly Kuhn Collection", imgSrc: "/assets/cloned/images/43ff456cfff8.jpg", description: "Winking Diamonds" },
    { alt: "Dainty Rose — Carly Kuhn Collection", imgSrc: "/assets/cloned/images/d91744a344ae.jpg", description: "Dainty Rose" },
    { alt: "Circus Circus — Carly Kuhn Collection", imgSrc: "/assets/cloned/images/2265a2baa993.jpg", description: "Circus Circus" }
];
const MediaCard2_data = [
    { alt: "Sheer lining swatch", imgSrc: "/assets/cloned/images/f38634a53925.jpg", text: "Fabric choice", title: "Sheer", description: "Choose a sheer fabric for the softest diffused light and an airy presence in the room." },
    { alt: "Unlined fabric swatch", imgSrc: "/assets/cloned/images/4469ddd4e7a8.jpg", text: "Fabric-focused", title: "Unlined", description: "Fabric-focused, with gentle daytime privacy and warm, filtered light." },
    { alt: "Privacy lining swatch", imgSrc: "/assets/cloned/images/053fee160997.jpg", text: "Lining added", title: "Privacy", description: "A lining added to your selected fabric — blocks sightlines while diffusing soft, ambient light through." },
    { alt: "Blackout lining swatch", imgSrc: "/assets/cloned/images/d70f7b71316f.jpg", text: "Lining added", title: "Blackout", description: "A lining added to your selected fabric — room-darkening for bedrooms, media rooms, and sleep spaces." }
];
const MediaCard3_data = [
    { alt: "Chain loop shade control", imgSrc: "/assets/cloned/images/0823beef28ea.jpg", title: "Chain Loop", description: "An antique brass metal chain, structured in a continuous loop. Durable and precise." },
    { alt: "Cordless shade control", imgSrc: "/assets/cloned/images/a8bb9eab2122.jpg", title: "Cordless", description: "Operated by a wooden tassel that sits on the back of the shade at the bottom center — a retracting cordless mechanism, not a manual push-and-pull. Child- and pet-safe by design." },
    { alt: "Motorized shade control", imgSrc: "/assets/cloned/images/fcd513f6320f.jpg", title: "Motorization", description: "Remote shade operation with the press of a button. A luxury experience — ideal for hard-to-reach or tall windows." }
];
const MediaCard4_data = [
    { alt: "Inside mount step 01 — depth requirement", imgSrc: "/assets/cloned/images/88fa97881aaa.jpg", description: "Step 01", title: "Depth requirement — 2.5\" minimum", description2: "We require 2.5\" of depth to inside mount. Measure the flat mounting surface available on your window." },
    { alt: "Inside mount step 02 — window width", imgSrc: "/assets/cloned/images/885bb47eafa5.jpg", description: "Step 02", title: "Window width", description2: "Rounding to the nearest ⅛\", measure in three places — top, middle, and bottom. Use the narrowest." },
    { alt: "Inside mount step 03 — window height", imgSrc: "/assets/cloned/images/41b79c5850a1.jpg", description: "Step 03", title: "Window height", description2: "Rounding to the nearest ⅛\", measure in three places — left, middle, and right. Use the longest." }
];
const MediaCard4_data2 = [
    { alt: "Outside mount step 01", imgSrc: "/assets/cloned/images/40ad7bbd26c2.jpg", description: "Step 01", title: "Window width", description2: "Measure across the finished window frame, rounded to the nearest ⅛\"." },
    { alt: "Outside mount step 02", imgSrc: "/assets/cloned/images/432c12591ccb.jpg", description: "Step 02", title: "Window height", description2: "Measure the height of the finished window frame, rounded to the nearest ⅛\"." },
    { alt: "Outside mount step 03", imgSrc: "/assets/cloned/images/44fda8d8d505.jpg", description: "Step 03", title: "Add mounting height", description2: "For wall mount — the most common — we suggest 5\". If trim projection is greater than ¾\", reach out for a custom solution." }
];
const MediaCard4_data3 = [
    { alt: "Door mount step 01", imgSrc: "/assets/cloned/images/e4b9ca6089ca.jpg", description: "Step 01", title: "Window width", description2: "Measure the glass width on the door, rounded to the nearest ⅛\"." },
    { alt: "Door mount step 02", imgSrc: "/assets/cloned/images/488de0ed21e0.jpg", description: "Step 02", title: "Window height", description2: "Measure the glass height on the door, rounded to the nearest ⅛\"." },
    { alt: "Door mount step 03", imgSrc: "/assets/cloned/images/14a6574e02b2.jpg", description: "Step 03", title: "Add mounting height", description2: "For door mount, we suggest 3\"–4\" above the glass, depending on the space available." }
];
const CardLink_meta: string[][] = [
    ["n39", "n40", "n41", "n42", "n43", "style-link-6", "style-link-7", "n46", "n47"],
    ["n48", "n49", "n50", "n51", "style-button", "style-button-2", "n54", "n55", "n56"],
    ["n57", "n58", "n59", "style-div-2", "n61", "style-div-3", "n63", "style-div-4", "n65"]
];
const Tile_meta: string[][] = [
    ["n71"],
    ["n72"],
    ["n73"],
    ["n74"],
    ["style-p"],
    ["n76"]
];
const ListRow_meta: string[][] = [
    ["n85", "style-link-8"],
    ["n87", "style-link-9"],
    ["n89", "n90"],
    ["n91", "n92"],
    ["style-link-10", "n94"],
    ["style-link-11", "n96"],
    ["n97", "n98"]
];
const MediaCard_meta: string[][] = [
    ["n114", "n115", "n116", "n117", "n118"],
    ["n119", "n120", "n121", "n122", "n123"],
    ["n124", "n125", "n126", "n127", "n128"],
    ["n129", "n130", "n131", "n132", "n133"],
    ["n134", "n135", "n136", "n137", "n138"],
    ["n139", "n140", "n141", "n142", "n143"]
];
const MediaTile_meta: string[][] = [
    ["n158", "n159", "n160"],
    ["n161", "n162", "n163"],
    ["n164", "n165", "n166"],
    ["n167", "n168", "n169"],
    ["n170", "n171", "n172"],
    ["n173", "n174", "n175"],
    ["n176", "n177", "n178"]
];
const MediaTile_meta2: string[][] = [
    ["n185", "n186", "n187"],
    ["n188", "n189", "n190"],
    ["n191", "n192", "n193"],
    ["n194", "n195", "n196"],
    ["n197", "n198", "n199"],
    ["n200", "n201", "n202"],
    ["n203", "n204", "n205"]
];
const MediaTile2_meta: string[][] = [
    ["n211", "n212", "n213"],
    ["n214", "n215", "n216"],
    ["n217", "n218", "n219"],
    ["n220", "n221", "n222"],
    ["n223", "n224", "n225"],
    ["n226", "n227", "n228"],
    ["n229", "n230", "n231"],
    ["n232", "n233", "n234"],
    ["n235", "n236", "n237"],
    ["n238", "n239", "n240"],
    ["n241", "n242", "n243"],
    ["n244", "n245", "n246"],
    ["n247", "n248", "n249"],
    ["n250", "n251", "n252"],
    ["n253", "n254", "n255"]
];
const MediaTile_meta3: string[][] = [
    ["n262", "n263", "n264"],
    ["n265", "n266", "n267"],
    ["n268", "n269", "n270"]
];
const MediaTile_meta4: string[][] = [
    ["n277", "n278", "n279"],
    ["n280", "n281", "n282"],
    ["n283", "n284", "n285"],
    ["n286", "n287", "n288"]
];
const MediaCard2_meta: string[][] = [
    ["n298", "n299", "n300", "n301", "n302", "n303"],
    ["n304", "n305", "n306", "n307", "n308", "n309"],
    ["n310", "n311", "n312", "n313", "n314", "n315"],
    ["n316", "n317", "n318", "n319", "n320", "n321"]
];
const MediaCard3_meta: string[][] = [
    ["n356", "n357", "n358", "n359", "n360"],
    ["n361", "n362", "n363", "n364", "n365"],
    ["n366", "n367", "n368", "n369", "n370"]
];
const MediaCard4_meta: string[][] = [
    ["n405", "n406", "n407", "n408", "n409", "n410"],
    ["n411", "n412", "n413", "n414", "n415", "n416"],
    ["n417", "n418", "n419", "n420", "n421", "n422"]
];
const MediaCard4_meta2: string[][] = [
    ["n430", "n431", "n432", "n433", "n434", "n435"],
    ["n436", "n437", "n438", "n439", "n440", "n441"],
    ["n442", "n443", "n444", "n445", "n446", "n447"]
];
const MediaCard4_meta3: string[][] = [
    ["n492", "n493", "n494", "n495", "n496", "n497"],
    ["n498", "n499", "n500", "n501", "n502", "n503"],
    ["n504", "n505", "n506", "n507", "n508", "n509"]
];
const Tile_styles = [
    { className: "after:w-[57.3594px] after: after:origin-[28.6797px_1px]" },
    { className: "after:w-[65.7188px] after:transform-[matrix(0,0,0,1,0,0)] after:origin-[32.8594px_1px]" },
    { className: "after:w-[118.047px] after:transform-[matrix(0,0,0,1,0,0)] after:origin-[59.0234px_1px]" },
    { className: "after:w-[123.156px] after:transform-[matrix(0,0,0,1,0,0)] after:origin-[61.5781px_1px]" },
    { className: "after:w-[81.375px] after:transform-[matrix(0,0,0,1,0,0)] after:origin-[40.6875px_1px]" },
    { className: "after:w-[9.3965rem] after:transform-[matrix(0,0,0,1,0,0)] after:origin-[75.1719px_1px]" }
];
const MediaTile2_styles = [
    { className: "w-full" },
    { className: "w-full" },
    { className: "w-32 max-lg:w-24" },
    { className: "w-32 max-lg:w-24" },
    { className: "w-full" },
    { className: "w-full" },
    { className: "w-full" },
    { className: "w-full" },
    { className: "w-full" },
    { className: "w-full" },
    { className: "w-full" },
    { className: "w-full" },
    { className: "w-full" },
    { className: "w-full" },
    { className: "w-full" }
];
const MediaCard2_styles = [
    { className: "bg-accent" },
    { className: "bg-clr-18" },
    { className: "bg-clr-19" },
    { className: "bg-clr-20" }
];

export default function Page() {
  return (
    <>
      <section className="grid relative grid-cols-[minmax(20px,1fr)_minmax(0,1400px)_minmax(20px,1fr)] max-md:grid-cols-[16px_343px_16px] md:max-lg:grid-cols-[16px_736px_16px]" data-ditto-id="style-shopify-section-template-20207705292962-main" aria-hidden="true" id="shopify-section-template--20207706308770__everhem_guidance_header_jWHx4i">
        <section className="block mt-30 py-16 col-span-full bg-accent max-lg:py-10">
          <div className="h-full block max-w-350 px-8 max-md:px-4 md:max-lg:px-6">
            <div className="block max-w-184 mb-[3.2rem] mx-auto text-center max-lg:mb-8">
              <h1 className="block [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-[3.1875rem] font-light italic leading-[3.375rem] tracking-[-0.51px] [overflow-wrap:break-word] max-lg:text-[2rem] max-lg:leading-[2.125rem] max-lg:tracking-[-0.32px]" data-component="heading">
                Your Partner in Design
              </h1>
              <p className="block max-w-160 mt-2 mx-auto text-color-011 font-light leading-[1.625rem] [overflow-wrap:break-word]">
                Our expertise meets your vision.
              </p>
            </div>
            <div className="grid gap-8 grid-cols-3 max-lg:gap-5 max-lg:grid-cols-1">
              {CardLink_data.map((d, i) => <CardLink key={i} d={d} />)}
            </div>
          </div>
          {" "}
        </section>
        {" "}
      </section>
      <section className="grid relative grid-cols-[minmax(20px,1fr)_minmax(0,1400px)_minmax(20px,1fr)] max-md:grid-cols-[16px_343px_16px] md:max-lg:grid-cols-[16px_736px_16px]" data-ditto-id="style-shopify-section-template-20207706308770-tabs" aria-hidden="true" id="shopify-section-template--20207706308770__tabs">
        <section className="block pt-5 pb-20 px-12 col-span-full bg-accent max-md:px-4 md:max-lg:px-[1.92rem]">
          <div className="h-full block max-w-350" data-ditto-id="style-div-5">
            <header className="flex mb-12 flex-col items-center gap-4 text-center" />
            {" "}
            <div className="border-b border-solid border-b-primary flex mb-2 justify-center gap-8 overflow-auto max-lg:justify-start max-lg:gap-5" data-ditto-id="style-div-6" role="tablist">
              {Tile_data.map((d, i) => <Tile key={i} d={d} styles={Tile_styles[i]} />)}
            </div>
            {" "}
            <div className="h-full block" data-ditto-id="style-div-7">
              <div className="h-full block [animation-name:tabFadeIn] [animation-duration:0.32s]" id="tab-t-1" role="tabpanel">
                <div className="grid items-center gap-16 grid-cols-2 max-lg:gap-8 max-lg:grid-cols-1" data-ditto-id="style-div-8">
                  <div className="flex flex-col gap-4" />
                  {" "}
                </div>
                {"  "}
                <div className="h-full block -mx-12 max-md:-mx-4 md:max-lg:-mx-[1.92rem]" data-ditto-id="style-shades-guide-top" id="shades-guide-top">
                  <nav className="border-b border-solid border-b-primary block bg-background" data-component="nav" aria-label="Shades guide sections">
                    <div className="block max-w-350 px-12 max-md:px-4 md:max-lg:px-[1.92rem]">
                      <ul className="flex justify-center gap-11 overflow-auto [list-style-type:none] max-lg:justify-start max-md:gap-4 md:max-lg:gap-[1.68rem]">
                        {ListRow_data.map((d, i) => <ListRow key={i} d={d} />)}
                      </ul>
                      {" "}
                    </div>
                    {" "}
                  </nav>
                  <section className="block pt-[5.6rem] pb-12 text-center max-md:pt-12 max-lg:pb-8 md:max-lg:pt-[3.36rem]">
                    <div className="block max-w-350 px-12 max-md:px-4 md:max-lg:px-[1.92rem]">
                      <p className="block mb-8 text-xs font-medium leading-[1.1875rem] tracking-[2.16px] uppercase [overflow-wrap:break-word]">
                        Your guide to shades — by Everhem experts
                      </p>
                      {" "}
                      <h1 className="block mb-8 [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-[4.8125rem] italic leading-[4.8125rem] tracking-[-1.15px] [overflow-wrap:break-word] max-md:text-[2.75rem] max-md:leading-11 max-md:tracking-[-0.66px] md:max-lg:text-[2.875rem] md:max-lg:leading-[2.875rem] md:max-lg:tracking-[-0.69px]" data-ditto-id="style-subscribe" data-component="heading">
                        The Shades Guide
                      </h1>
                      {" "}
                      <p className="block max-w-[26.64rem] mx-auto text-color-003 font-light leading-[1.625rem] [overflow-wrap:break-word]">
                        {"\n        A considered walk-through of every decision that shapes a custom shade —\n        from fabric and style to how it opens, where it sits, and how you live with it.\n      "}
                      </p>
                      {" "}
                    </div>
                    {" "}
                    <div className="block max-w-350 px-12 max-md:px-4 md:max-lg:px-[1.92rem]">
                      <div className="block relative mt-16 overflow-hidden bg-accent aspect-video max-md:mt-8 md:max-lg:mt-[2.4rem]" data-ditto-id="style-div">
                        <img className="w-full h-166.5 block max-w-full overflow-clip object-cover aspect-[auto_1200/900] max-md:h-48 md:max-lg:h-[24.8125rem]" data-component="image" alt="An interior featuring custom Everhem shades." height="900" src="/assets/cloned/images/ef3a2fa27b61.jpg" width="1200" />
                        {" "}
                      </div>
                      {" "}
                    </div>
                    {" "}
                  </section>
                  <section className="border-t border-solid border-t-primary block py-[5.6rem] max-lg:py-14" data-ditto-id="style-shades-guide-shade-type" id="shades-guide-shade-type">
                    <div className="block max-w-350 px-12 max-md:px-4 md:max-lg:px-[1.92rem]">
                      <header className="w-full max-w-[497.27px] flex mb-12 flex-col gap-4 max-lg:mb-8" data-ditto-id="style-header">
                        <p className="block [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-sm italic leading-[1.375rem] tracking-[0.56px] [overflow-wrap:break-word]">
                          01 — Shade Type
                        </p>
                        {" "}
                        <h2 className="block [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-[3.625rem] italic leading-[3.75rem] tracking-[-0.58px] [overflow-wrap:break-word] max-md:text-[2rem] max-md:leading-[2.125rem] max-md:tracking-[-0.32px] md:max-lg:text-[2.1875rem] md:max-lg:leading-[2.25rem] md:max-lg:tracking-[-0.35px]" data-component="heading">
                          Start with the style.
                        </h2>
                        {" "}
                        <p className="block text-color-003 font-light leading-[1.625rem] [overflow-wrap:break-word]">
                          {"\n          The silhouette sets the tone. Begin here — every decision that follows builds on the style you choose.\n        "}
                        </p>
                        {" "}
                      </header>
                      {" "}
                      <div className="grid gap-y-[2.4rem] gap-x-8 grid-cols-[repeat(auto-fit,_minmax(283px,_1fr))] grid-rows-2 max-lg:gap-y-6 max-lg:gap-x-5 max-md:grid-rows-6 md:max-lg:grid-rows-3">
                        {MediaCard_data.map((d, i) => <MediaCard key={i} d={d} />)}
                      </div>
                      {" "}
                    </div>
                    {" "}
                  </section>
                  <section className="border-t border-solid border-t-primary block py-[4.8rem] px-[3.2rem] bg-accent max-lg:py-12 max-md:px-6 md:max-lg:px-[1.92rem]" id="shades-guide-fabric">
                    <div className="block max-w-350 px-12 max-md:px-4 md:max-lg:px-[1.92rem]">
                      <header className="w-full max-w-[497.27px] flex mb-12 flex-col gap-4 max-lg:mb-8">
                        <p className="block [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-sm italic leading-[1.375rem] tracking-[0.56px] [overflow-wrap:break-word]">
                          {"02 — Fabric & Color"}
                        </p>
                        {" "}
                        <h2 className="block [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-[3.625rem] italic leading-[3.75rem] tracking-[-0.58px] [overflow-wrap:break-word] max-md:text-[2rem] max-md:leading-[2.125rem] max-md:tracking-[-0.32px] md:max-lg:text-[2.1875rem] md:max-lg:leading-[2.25rem] md:max-lg:tracking-[-0.35px]" data-component="heading">
                          Which fabric is best for you?
                        </h2>
                        {" "}
                        <p className="block text-color-003 font-light leading-[1.625rem] [overflow-wrap:break-word]">
                          {"\n          Explore our designer-curated collections organized by hand, weave, and finish.\n          See it in your space before you decide.\n        "}
                        </p>
                        {" "}
                      </header>
                      {"  "}
                      <div className="block">
                        <div className="flex flex-col gap-16">
                          <div className="grid items-start gap-8 grid-cols-[280px_1fr] max-lg:gap-4 max-lg:grid-cols-1">
                            <div className="h-[61.7812px] block sticky top-28 max-lg:static">
                              <p className="block mb-1 text-xs font-medium leading-[1.1875rem] tracking-[1.44px] uppercase [overflow-wrap:break-word]">
                                Everhem Hues
                              </p>
                              {" "}
                              <p className="block mb-0.5 text-color-016 text-xs leading-[1.1875rem] [overflow-wrap:break-word]">
                                100% Belgian Linen
                              </p>
                              {" "}
                              <p className="block text-color-021 text-xs leading-[1.1875rem] [overflow-wrap:break-word]">
                                7 fabrics
                              </p>
                              {" "}
                            </div>
                            {" "}
                            <div className="flex pb-2 gap-2 overflow-auto">
                              {MediaTile_data.map((d, i) => <MediaTile key={i} d={d} />)}
                            </div>
                            {" "}
                          </div>
                          <div className="grid items-start gap-8 grid-cols-[280px_1fr] max-lg:gap-4 max-lg:grid-cols-1">
                            <div className="h-[61.7812px] block sticky top-28 max-lg:static">
                              <p className="block mb-1 text-xs font-medium leading-[1.1875rem] tracking-[1.44px] uppercase [overflow-wrap:break-word]">
                                Everhem Essentials
                              </p>
                              {" "}
                              <p className="block mb-0.5 text-color-016 text-xs leading-[1.1875rem] [overflow-wrap:break-word]">
                                65% Linen, 35% Cotton
                              </p>
                              {" "}
                              <p className="block text-color-021 text-xs leading-[1.1875rem] [overflow-wrap:break-word]">
                                7 fabrics
                              </p>
                              {" "}
                            </div>
                            {" "}
                            <div className="flex pb-2 gap-2 overflow-auto">
                              {MediaTile_data2.map((d, i) => <MediaTile key={i} d={d} />)}
                            </div>
                            {" "}
                          </div>
                          <div className="grid items-start gap-8 grid-cols-[280px_1fr] max-lg:gap-4 max-lg:grid-cols-1">
                            <div className="h-[41.1875px] block sticky top-28 max-lg:static">
                              <p className="block mb-1 text-xs font-medium leading-[1.1875rem] tracking-[1.44px] uppercase [overflow-wrap:break-word]">
                                Jake Arnold for Everhem
                              </p>
                              {" "}
                              <p className="block text-color-021 text-xs leading-[1.1875rem] [overflow-wrap:break-word]">
                                11 fabrics
                              </p>
                              {" "}
                            </div>
                            {" "}
                            <div className="flex pb-2 gap-2 overflow-auto">
                              {MediaTile2_data.map((d, i) => <MediaTile2 key={i} d={d} styles={MediaTile2_styles[i]} />)}
                            </div>
                            {" "}
                          </div>
                          <div className="grid items-start gap-8 grid-cols-[280px_1fr] max-lg:gap-4 max-lg:grid-cols-1">
                            <div className="h-[61.7812px] block sticky top-28 max-lg:static">
                              <p className="block mb-1 text-xs font-medium leading-[1.1875rem] tracking-[1.44px] uppercase [overflow-wrap:break-word]">
                                Sheers
                              </p>
                              {" "}
                              <p className="block mb-0.5 text-color-016 text-xs leading-[1.1875rem] [overflow-wrap:break-word]">
                                54% Linen, 32% Cotton, 14% Polyester
                              </p>
                              {" "}
                              <p className="block text-color-021 text-xs leading-[1.1875rem] [overflow-wrap:break-word]">
                                3 fabrics
                              </p>
                              {" "}
                            </div>
                            {" "}
                            <div className="flex pb-2 gap-2 overflow-auto">
                              {MediaTile_data3.map((d, i) => <MediaTile key={i} d={d} />)}
                            </div>
                            {" "}
                          </div>
                          <div className="grid items-start gap-8 grid-cols-[280px_1fr] max-lg:gap-4 max-lg:grid-cols-1">
                            <div className="h-[61.7812px] block sticky top-28 max-lg:static">
                              <p className="block mb-1 text-xs font-medium leading-[1.1875rem] tracking-[1.44px] uppercase [overflow-wrap:break-word]">
                                Carly Kuhn Collection
                              </p>
                              {" "}
                              <p className="block mb-0.5 text-color-016 text-xs leading-[1.1875rem] [overflow-wrap:break-word]">
                                95% Linen, 5% Cotton
                              </p>
                              {" "}
                              <p className="block text-color-021 text-xs leading-[1.1875rem] [overflow-wrap:break-word]">
                                4 fabrics
                              </p>
                              {" "}
                            </div>
                            {" "}
                            <div className="flex pb-2 gap-2 overflow-auto">
                              {MediaTile_data4.map((d, i) => <MediaTile key={i} d={d} />)}
                            </div>
                            {" "}
                          </div>
                          {" "}
                        </div>
                        <div className="block mt-12 text-center">
                          <a className="inline-block py-4 px-8 text-background text-xs font-medium leading-[1.1875rem] tracking-[1.44px] uppercase bg-color-002 cursor-pointer" data-component="button" href="/pages/samples">
                            Order free swatches
                          </a>
                          {" "}
                        </div>
                      </div>
                      {" "}
                    </div>
                    {" "}
                  </section>
                  <section className="border-t border-solid border-t-primary block py-[5.6rem] max-lg:py-14" id="shades-guide-lining">
                    <div className="block max-w-350 px-12 max-md:px-4 md:max-lg:px-[1.92rem]">
                      <header className="w-full max-w-[497.27px] flex mb-12 flex-col gap-4 max-lg:mb-8">
                        <p className="block [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-sm italic leading-[1.375rem] tracking-[0.56px] [overflow-wrap:break-word]">
                          03 — Lining
                        </p>
                        {" "}
                        <h2 className="block [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-[3.625rem] italic leading-[3.75rem] tracking-[-0.58px] [overflow-wrap:break-word] max-md:text-[2rem] max-md:leading-[2.125rem] max-md:tracking-[-0.32px] md:max-lg:text-[2.1875rem] md:max-lg:leading-[2.25rem] md:max-lg:tracking-[-0.35px]" data-component="heading">
                          Choose your lining.
                        </h2>
                        {" "}
                        <p className="block text-color-003 font-light leading-[1.625rem] [overflow-wrap:break-word]">
                          {"\n          Lining determines how much light moves through your shade. Choose based on the function of your space,\n          how it's used, and how much privacy and light control you want.\n        "}
                        </p>
                        {" "}
                      </header>
                      {" "}
                      <div className="grid gap-6 grid-cols-4 max-lg:gap-4 max-md:grid-cols-1 md:max-lg:grid-cols-2">
                        {MediaCard2_data.map((d, i) => <MediaCard2 key={i} d={d} styles={MediaCard2_styles[i]} />)}
                        {" "}
                      </div>
                      {" "}
                    </div>
                    {" "}
                  </section>
                  <section className="border-t border-solid border-t-primary block py-[5.6rem] max-lg:py-14" id="shades-guide-mount">
                    <div className="block max-w-350 px-12 max-md:px-4 md:max-lg:px-[1.92rem]">
                      <header className="w-full max-w-[497.27px] flex mb-12 flex-col gap-4 max-lg:mb-8">
                        <p className="block [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-sm italic leading-[1.375rem] tracking-[0.56px] [overflow-wrap:break-word]">
                          04 — Mount Position
                        </p>
                        {" "}
                        <h2 className="block [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-[3.625rem] italic leading-[3.75rem] tracking-[-0.58px] [overflow-wrap:break-word] max-md:text-[2rem] max-md:leading-[2.125rem] max-md:tracking-[-0.32px] md:max-lg:text-[2.1875rem] md:max-lg:leading-[2.25rem] md:max-lg:tracking-[-0.35px]" data-component="heading">
                          Inside or outside mount.
                        </h2>
                        {" "}
                        <p className="block text-color-003 font-light leading-[1.625rem] [overflow-wrap:break-word]">
                          Where the shade lives on your window.
                        </p>
                        {" "}
                      </header>
                      {" "}
                      <div className="grid items-start gap-y-[3.2rem] gap-x-16 grid-cols-[1.05fr_1fr] max-md:gap-8 max-lg:grid-cols-1 md:max-lg:gap-y-8 md:max-lg:gap-x-[2.4rem]">
                        <div className="block relative col-start-1 row-start-1 overflow-hidden bg-accent aspect-[4/3] max-lg:[grid-row-start:initial]">
                          <img className="w-full h-107.5 block max-w-full overflow-clip object-cover aspect-[auto_1200/900] max-md:h-64 md:max-lg:h-132.5" data-component="image" alt="Inside-mount shade installed within the window frame" height="900" src="/assets/cloned/images/bccccae0f3b2.jpg" width="1200" />
                          {" "}
                        </div>
                        {" "}
                        <div className="flex pt-[2.4rem] flex-col gap-4 col-start-2 row-start-1 max-lg:col-start-1 max-lg:pt-0 max-lg:[grid-row-start:initial]">
                          <h3 className="block [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-[1.9375rem] italic leading-[2.1875rem] tracking-[-0.15px] [overflow-wrap:break-word] max-lg:text-2xl max-lg:leading-[1.75rem] max-lg:tracking-[-0.12px]" data-component="heading">
                            Inside Mount
                          </h3>
                          {" "}
                          <p className="block font-light leading-[1.625rem] [overflow-wrap:break-word]">
                            Sits inside the window frame for a clean, built-in look.
                          </p>
                          {" "}
                          <p className="block text-sm font-light italic leading-[1.375rem] [overflow-wrap:break-word]">
                            Best for: trim you want to show, deeper windows, architectural moments.
                          </p>
                          {" "}
                          <div className="border-l-2 border-solid border-l-foreground flex mt-4 py-5 px-8 flex-col gap-2 bg-accent">
                            <p className="block text-[0.6875rem] leading-[1.0625rem] tracking-[1.98px] uppercase [overflow-wrap:break-word]">
                              Depth requirement
                            </p>
                            {" "}
                            <p className="block [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-2xl italic leading-[2.3125rem] [overflow-wrap:break-word]">
                              2.5" minimum
                            </p>
                            {" "}
                            <p className="block text-sm font-light leading-[1.375rem] [overflow-wrap:break-word]">
                              We require 2.5" of depth to inside mount. Measure the flat mounting surface available on your window.
                            </p>
                            {" "}
                          </div>
                          {" "}
                        </div>
                        {" "}
                        <div className="flex pt-[2.4rem] flex-col gap-4 col-start-1 row-start-2 max-lg:pt-0 max-lg:[grid-row-start:initial]">
                          <h3 className="block [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-[1.9375rem] italic leading-[2.1875rem] tracking-[-0.15px] [overflow-wrap:break-word] max-lg:text-2xl max-lg:leading-[1.75rem] max-lg:tracking-[-0.12px]" data-component="heading">
                            Outside Mount
                          </h3>
                          {" "}
                          <p className="block font-light leading-[1.625rem] [overflow-wrap:break-word]">
                            Installs on the wall or trim above the window. Covers more area and blocks more light.
                          </p>
                          {" "}
                          <p className="block text-sm font-light italic leading-[1.375rem] [overflow-wrap:break-word]">
                            Best for: shallow windows, hiding imperfect trim, maximum light control.
                          </p>
                          {" "}
                          <div className="border-l-2 border-solid border-l-foreground flex mt-4 py-5 px-8 flex-col gap-2 bg-accent">
                            <p className="block text-[0.6875rem] leading-[1.0625rem] tracking-[1.98px] uppercase [overflow-wrap:break-word]">
                              Projection
                            </p>
                            {" "}
                            <p className="block [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-2xl italic leading-[2.3125rem] [overflow-wrap:break-word]">
                              2"–3" from the wall
                            </p>
                            {" "}
                            <p className="block text-sm font-light leading-[1.375rem] [overflow-wrap:break-word]">
                              Shades will have a 2"–3" projection depending on shade width.
                            </p>
                            {" "}
                          </div>
                          {" "}
                        </div>
                        {" "}
                        <div className="block relative col-start-2 row-start-2 overflow-hidden bg-accent aspect-[4/3] max-lg:col-start-1 max-lg:[grid-row-start:initial]">
                          <img className="w-full h-102.5 block max-w-full overflow-clip object-cover aspect-[auto_1200/900] max-md:h-64 md:max-lg:h-132.5" data-component="image" alt="Outside-mount shade installed above the window frame" height="900" src="/assets/cloned/images/8b66fada8288.jpg" width="1200" />
                          {" "}
                        </div>
                        {" "}
                      </div>
                    </div>
                    {" "}
                  </section>
                  <section className="border-t border-solid border-t-primary block py-[5.6rem] max-lg:py-14" id="shades-guide-control">
                    <div className="block max-w-350 px-12 max-md:px-4 md:max-lg:px-[1.92rem]">
                      <header className="w-full max-w-[497.27px] flex mb-12 flex-col gap-4 max-lg:mb-8">
                        <p className="block [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-sm italic leading-[1.375rem] tracking-[0.56px] [overflow-wrap:break-word]">
                          05 — Custom Control
                        </p>
                        {" "}
                        <h2 className="block [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-[3.625rem] italic leading-[3.75rem] tracking-[-0.58px] [overflow-wrap:break-word] max-md:text-[2rem] max-md:leading-[2.125rem] max-md:tracking-[-0.32px] md:max-lg:text-[2.1875rem] md:max-lg:leading-[2.25rem] md:max-lg:tracking-[-0.35px]" data-component="heading">
                          How your shade opens.
                        </h2>
                        {" "}
                        <p className="block text-color-003 font-light leading-[1.625rem] [overflow-wrap:break-word]">
                          {"\n          The control is the part you'll touch every day. Choose based on how the space is used — and who uses it.\n        "}
                        </p>
                        {" "}
                      </header>
                      {" "}
                      <div className="grid gap-[2.4rem] grid-cols-3 max-lg:gap-6 max-lg:grid-cols-1">
                        {MediaCard3_data.map((d, i) => <MediaCard3 key={i} d={d} />)}
                        {" "}
                      </div>
                      {" "}
                    </div>
                    {" "}
                  </section>
                  <section className="border-t border-solid border-t-primary block py-[5.6rem] max-lg:py-14" id="shades-guide-operation">
                    <div className="block max-w-350 px-12 max-md:px-4 md:max-lg:px-[1.92rem]">
                      <header className="w-full max-w-[497.27px] flex mb-12 flex-col gap-4 max-lg:mb-8">
                        <p className="block [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-sm italic leading-[1.375rem] tracking-[0.56px] [overflow-wrap:break-word]">
                          06 — Shade Operation
                        </p>
                        {" "}
                        <h2 className="block [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-[3.625rem] italic leading-[3.75rem] tracking-[-0.58px] [overflow-wrap:break-word] max-md:text-[2rem] max-md:leading-[2.125rem] max-md:tracking-[-0.32px] md:max-lg:text-[2.1875rem] md:max-lg:leading-[2.25rem] md:max-lg:tracking-[-0.35px]" data-component="heading">
                          Front or back.
                        </h2>
                        {" "}
                        <p className="block text-color-003 font-light leading-[1.625rem] [overflow-wrap:break-word]">
                          {"\n          How the shade is constructed on the headrail — how the fabric falls toward the room or toward the window.\n        "}
                        </p>
                        {" "}
                      </header>
                      {" "}
                      <div className="grid gap-[3.2rem] grid-cols-2 max-lg:gap-8 max-lg:grid-cols-1">
                        <div className="block relative col-start-1 overflow-hidden bg-accent aspect-[5/4]">
                          <img className="w-full h-[28.3125rem] block max-w-full overflow-clip object-cover aspect-[auto_1200/900] max-md:h-68.5 md:max-lg:h-[35.3125rem]" data-component="image" alt="Front-fall shade construction" height="900" src="/assets/cloned/images/994009ca902c.jpg" width="1200" />
                          {" "}
                        </div>
                        {" "}
                        <div className="flex max-w-[26.64rem] pt-[4.8rem] flex-col gap-4 col-start-2 max-lg:col-start-1 max-lg:max-w-none max-lg:pt-0">
                          <h3 className="block [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-[1.9375rem] italic leading-[2.1875rem] tracking-[-0.15px] [overflow-wrap:break-word] max-lg:text-2xl max-lg:leading-[1.75rem] max-lg:tracking-[-0.12px]" data-component="heading">
                            Front
                          </h3>
                          {" "}
                          <p className="block font-light leading-[1.625rem] [overflow-wrap:break-word]">
                            The fabric falls off the back of the headrail, and a valance is added in the front to conceal the hardware.
                          </p>
                          {" "}
                          <p className="block text-sm font-light italic leading-[1.375rem] [overflow-wrap:break-word]">
                            If Chain Loop is selected, the chain is visible when the shade is drawn closed — for easy access when opening or closing.
                          </p>
                          {" "}
                          <p className="block text-sm font-light italic leading-[1.375rem] [overflow-wrap:break-word]">
                            Recommended for outside-mount shades with blackout lining.
                          </p>
                          {" "}
                        </div>
                        {" "}
                        <div className="flex max-w-[26.64rem] pt-[6.4rem] flex-col gap-4 col-start-1 max-lg:max-w-none max-lg:pt-0">
                          <h3 className="block [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-[1.9375rem] italic leading-[2.1875rem] tracking-[-0.15px] [overflow-wrap:break-word] max-lg:text-2xl max-lg:leading-[1.75rem] max-lg:tracking-[-0.12px]" data-component="heading">
                            Back
                          </h3>
                          {" "}
                          <p className="block font-light leading-[1.625rem] [overflow-wrap:break-word]">
                            The fabric falls off the front of the headrail — a waterfall with no valance.
                          </p>
                          {" "}
                          <p className="block text-sm font-light italic leading-[1.375rem] [overflow-wrap:break-word]">
                            If Chain Loop is selected, the control is featured in the front.
                          </p>
                          {" "}
                          <p className="block text-sm font-light italic leading-[1.375rem] [overflow-wrap:break-word]">
                            Note: no valance means that for outside mount, the projection is exposed. Shades will have a 2"–3" projection depending on shade width.
                          </p>
                          {" "}
                        </div>
                        {" "}
                        <div className="block relative mt-[6.4rem] col-start-2 overflow-hidden bg-accent aspect-[5/4] max-lg:col-start-1 max-lg:mt-0">
                          <img className="w-full h-[28.3125rem] block max-w-full overflow-clip object-cover aspect-[auto_1200/900] max-md:h-68.5 md:max-lg:h-[35.3125rem]" data-component="image" alt="Back-fall shade construction" height="900" src="/assets/cloned/images/805b21dc7948.jpg" width="1200" />
                          {" "}
                        </div>
                        {" "}
                      </div>
                      {" "}
                    </div>
                    {" "}
                  </section>
                  <section className="border-t border-solid border-t-primary block py-[5.6rem] text-accent bg-foreground max-lg:py-14" id="shades-guide-measure">
                    <div className="block max-w-350 px-12 max-md:px-4 md:max-lg:px-[1.92rem]">
                      <header className="w-full max-w-[497.27px] flex mb-12 flex-col gap-4 max-lg:mb-8">
                        <p className="block [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-sm italic leading-[1.375rem] tracking-[0.56px] [overflow-wrap:break-word]">
                          07 — How to Measure
                        </p>
                        {" "}
                        <h2 className="block [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-[3.625rem] italic leading-[3.75rem] tracking-[-0.58px] [overflow-wrap:break-word] max-md:text-[2rem] max-md:leading-[2.125rem] max-md:tracking-[-0.32px] md:max-lg:text-[2.1875rem] md:max-lg:leading-[2.25rem] md:max-lg:tracking-[-0.35px]" data-component="heading">
                          Measure like a pro.
                        </h2>
                        {" "}
                        <p className="block text-color-009 font-light leading-[1.625rem] [overflow-wrap:break-word]">
                          A tape measure is all you need.
                        </p>
                        {" "}
                        <p className="block mt-4 text-color-009 text-sm font-light leading-[1.375rem] [overflow-wrap:break-word]">
                          <strong className="inline mr-2 text-accent text-xs font-medium leading-[1.1875rem] tracking-[2.16px] uppercase">
                            Pro note —
                          </strong>
                          {" your tape measure needs ⅛\" tick marks visible.\n        "}
                        </p>
                        {" "}
                      </header>
                      <div className="border-t border-solid border-t-color-006 block py-[4.8rem] max-lg:py-12">
                        <header className="w-full max-w-[497.27px] block mb-11 max-lg:mb-8">
                          <h3 className="block mb-2 [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-[1.9375rem] italic leading-[2.1875rem] [overflow-wrap:break-word] max-lg:text-2xl max-lg:leading-[1.75rem]" data-component="heading">
                            Inside Mount
                          </h3>
                          {" "}
                          <p className="block opacity-75 text-color-009 text-sm font-light italic leading-[1.375rem] [overflow-wrap:break-word]">
                            Measured on the interior of the window frame.
                          </p>
                          {" "}
                        </header>
                        {" "}
                        <div className="grid gap-8 grid-cols-3 max-lg:gap-6 max-lg:grid-cols-1">
                          {MediaCard4_data.map((d, i) => <MediaCard4 key={i} d={d} />)}
                          {" "}
                        </div>
                        {" "}
                      </div>
                      {" "}
                    </div>
                    {" "}
                  </section>
                  <section className="block text-accent bg-foreground" aria-label="Outside mount measuring">
                    <div className="block max-w-350 px-12 max-md:px-4 md:max-lg:px-[1.92rem]">
                      <div className="border-t border-solid border-t-color-006 block py-[4.8rem] max-lg:py-12">
                        <header className="w-full max-w-[497.27px] block mb-11 max-lg:mb-8">
                          <h3 className="block mb-2 [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-[1.9375rem] italic leading-[2.1875rem] [overflow-wrap:break-word] max-lg:text-2xl max-lg:leading-[1.75rem]" data-component="heading">
                            Outside Mount
                          </h3>
                          {" "}
                          <p className="block opacity-75 text-color-009 text-sm font-light italic leading-[1.375rem] [overflow-wrap:break-word]">
                            Measured on the outline of the finished window frame, including trim.
                          </p>
                          {" "}
                        </header>
                        {" "}
                        <div className="grid gap-8 grid-cols-3 max-lg:gap-6 max-lg:grid-cols-1">
                          {MediaCard4_data2.map((d, i) => <MediaCard4 key={i} d={d} />)}
                          {" "}
                        </div>
                        {" "}
                        <div className="grid mt-6 gap-8 grid-cols-3 max-lg:mt-4 max-lg:gap-6 max-lg:grid-cols-1">
                          <div className="border-t border-solid border-color-006 border-r border-b border-l-2 flex p-6 flex-col gap-2 max-lg:p-4">
                            <p className="block text-[0.6875rem] leading-[1.0625rem] tracking-[1.98px] uppercase [overflow-wrap:break-word]">
                              Add width for coverage
                            </p>
                            {" "}
                            <p className="block opacity-75 text-color-009 text-sm font-light leading-[1.375rem] [overflow-wrap:break-word]">
                              We suggest 1"–2" per side for optimal coverage, especially with blackout lining.
                            </p>
                            {" "}
                            <div className="block relative overflow-hidden bg-accent aspect-[4/3]">
                              <img className="w-full h-60.5 block max-w-full overflow-clip object-cover aspect-[auto_1200/900] max-md:h-[14.4375rem] md:max-lg:h-126" data-component="image" alt="Outside-mount shade with added width coverage on each side" height="900" src="/assets/cloned/images/feb3e55553aa.jpg" width="1200" />
                              {" "}
                            </div>
                            {" "}
                          </div>
                          {" "}
                          <div className="border-t border-solid border-color-006 border-r border-b border-l-2 flex p-6 flex-col gap-2 max-lg:p-4">
                            <p className="block text-[0.6875rem] leading-[1.0625rem] tracking-[1.98px] uppercase [overflow-wrap:break-word]">
                              Add length for coverage
                            </p>
                            {" "}
                            <p className="block opacity-75 text-color-009 text-sm font-light leading-[1.375rem] [overflow-wrap:break-word]">
                              With no sill, add length to your window height equal to the additional width per side. Added 1" per side to width? Add 1" to height — before adding your mounting height.
                            </p>
                            {" "}
                          </div>
                          {" "}
                          <div className="border-t border-solid border-color-006 border-r border-b border-l-2 flex p-6 flex-col gap-2 max-lg:p-4">
                            <p className="block text-[0.6875rem] leading-[1.0625rem] tracking-[1.98px] uppercase [overflow-wrap:break-word]">
                              Mounting height guide
                            </p>
                            {" "}
                            <p className="block opacity-75 text-color-009 text-sm font-light leading-[1.375rem] [overflow-wrap:break-word]">
                              <strong className="inline text-accent font-medium">
                                Wall mount —
                              </strong>
                              {" 5\" above the window (most common)."}
                              <br className="inline" />
                              {" "}
                              <strong className="inline text-accent font-medium">
                                Trim mount —
                              </strong>
                              {" 0\" mounting height, flush with the top of the window trim."}
                              <br className="inline" />
                              {" "}
                              <strong className="inline text-accent font-medium">
                                Door mount —
                              </strong>
                              {" 3\"–4\" mounting height, depending on available space.\n            "}
                            </p>
                            {" "}
                          </div>
                          {" "}
                        </div>
                        <aside className="border border-solid border-color-006 block mt-12 p-[2.4rem] max-lg:mt-8 max-lg:p-6" aria-label="Sill measuring guide">
                          <p className="block mb-4 text-xs leading-[1.1875rem] tracking-[2.16px] uppercase [overflow-wrap:break-word]">
                            Sill guide
                          </p>
                          {" "}
                          <h4 className="block mb-2 [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-2xl italic leading-[1.75rem] [overflow-wrap:break-word] max-lg:text-xl max-lg:leading-[1.4375rem]" data-component="heading">
                            If your window has a sill, make the following adjustments.
                          </h4>
                          {" "}
                          <p className="block opacity-75 mb-8 text-sm font-light italic leading-[1.375rem] [overflow-wrap:break-word]">
                            Your sill becomes the reference point for width, height, and mounting.
                          </p>
                          {" "}
                          <div className="border-t border-solid border-t-color-006 grid pt-8 gap-8 grid-cols-3 max-lg:gap-6 max-lg:grid-cols-1">
                            <div className="border-l border-solid border-l-color-006 flex pl-5 flex-col gap-2 max-lg:border-t max-lg:border-t-color-006 max-lg:pt-4 max-lg:border-l-[0] max-lg:border-initial max-lg:border-l-[initial] max-lg:pl-0">
                              <p className="block opacity-70 [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-sm italic leading-[1.375rem] tracking-[0.56px] [overflow-wrap:break-word]">
                                Step 01 — Window width
                              </p>
                              {" "}
                              <h5 className="block [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-xl italic leading-[1.4375rem] [overflow-wrap:break-word]" data-component="heading">
                                Match your shade width to your sill width.
                              </h5>
                              {" "}
                              <p className="block opacity-75 text-color-009 text-sm font-light leading-[1.375rem] [overflow-wrap:break-word]">
                                Measure your sill at its widest point. This width becomes your final shade width.
                              </p>
                              {" "}
                            </div>
                            {" "}
                            <div className="border-l border-solid border-l-color-006 flex pl-5 flex-col gap-2 max-lg:border-t max-lg:border-t-color-006 max-lg:pt-4 max-lg:border-l-[0] max-lg:border-initial max-lg:border-l-[initial] max-lg:pl-0">
                              <p className="block opacity-70 [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-sm italic leading-[1.375rem] tracking-[0.56px] [overflow-wrap:break-word]">
                                Step 02 — Window height
                              </p>
                              {" "}
                              <h5 className="block [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-xl italic leading-[1.4375rem] [overflow-wrap:break-word]" data-component="heading">
                                Measure to the top of the sill.
                              </h5>
                              {" "}
                              <p className="block opacity-75 text-color-009 text-sm font-light leading-[1.375rem] [overflow-wrap:break-word]">
                                Measure from the top of the window frame to the top of the sill. The shade will stop at the sill.
                              </p>
                              {" "}
                            </div>
                            {" "}
                            <div className="border-l border-solid border-l-color-006 flex pl-5 flex-col gap-2 max-lg:border-t max-lg:border-t-color-006 max-lg:pt-4 max-lg:border-l-[0] max-lg:border-initial max-lg:border-l-[initial] max-lg:pl-0">
                              <p className="block opacity-70 [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-sm italic leading-[1.375rem] tracking-[0.56px] [overflow-wrap:break-word]">
                                Step 03 — Mounting height
                              </p>
                              {" "}
                              <h5 className="block [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-xl italic leading-[1.4375rem] [overflow-wrap:break-word]" data-component="heading">
                                Choose how you want to sit above the window.
                              </h5>
                              {" "}
                              <p className="block opacity-75 text-color-009 text-sm font-light leading-[1.375rem] [overflow-wrap:break-word]">
                                <strong className="inline font-normal">
                                  Trim out on the sill —
                                </strong>
                                {" choose 0\" mounting height."}
                                <br className="inline" />
                                {" "}
                                <strong className="inline font-normal">
                                  Mount above the window —
                                </strong>
                                {" choose 5\" mounting height.\n              "}
                              </p>
                              {" "}
                            </div>
                            {" "}
                          </div>
                          {" "}
                        </aside>
                        {" "}
                      </div>
                      {" "}
                    </div>
                    {" "}
                  </section>
                  <section className="block text-accent bg-foreground" aria-label="Door mount measuring">
                    <div className="block max-w-350 px-12 max-md:px-4 md:max-lg:px-[1.92rem]">
                      <div className="border-t border-solid border-t-color-006 block py-[4.8rem] max-lg:py-12">
                        <header className="w-full max-w-[497.27px] block mb-11 max-lg:mb-8">
                          <h3 className="block mb-2 [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-[1.9375rem] italic leading-[2.1875rem] [overflow-wrap:break-word] max-lg:text-2xl max-lg:leading-[1.75rem]" data-component="heading">
                            Door Mount
                          </h3>
                          {" "}
                          <p className="block opacity-75 text-color-009 text-sm font-light italic leading-[1.375rem] [overflow-wrap:break-word]">
                            For shades installed on a door with a glass insert — measured on the glass, not the door.
                          </p>
                          {" "}
                        </header>
                        {" "}
                        <div className="grid gap-8 grid-cols-3 max-lg:gap-6 max-lg:grid-cols-1">
                          {MediaCard4_data3.map((d, i) => <MediaCard4 key={i} d={d} />)}
                          {" "}
                        </div>
                        {" "}
                        <div className="grid mt-6 gap-8 grid-cols-3 max-lg:mt-4 max-lg:gap-6 max-lg:grid-cols-1">
                          <div className="border-t border-solid border-color-006 border-r border-b border-l-2 flex p-6 flex-col gap-2 max-lg:p-4">
                            <p className="block text-[0.6875rem] leading-[1.0625rem] tracking-[1.98px] uppercase [overflow-wrap:break-word]">
                              Add width for coverage
                            </p>
                            {" "}
                            <p className="block opacity-75 text-color-009 text-sm font-light leading-[1.375rem] [overflow-wrap:break-word]">
                              Add as much width as you can without hindering your door hardware — deadbolts, handles, or locks at the side of the glass.
                            </p>
                            {" "}
                            <div className="block relative overflow-hidden bg-accent aspect-[4/3]">
                              <img className="w-full h-60.5 block max-w-full overflow-clip object-cover aspect-[auto_1200/900] max-md:h-[14.4375rem] md:max-lg:h-126" data-component="image" alt="Door-mount shade with added width coverage" height="900" src="/assets/cloned/images/c3c49f64b23c.jpg" width="1200" />
                              {" "}
                            </div>
                            {" "}
                          </div>
                          {" "}
                          <div className="border-t border-solid border-color-006 border-r border-b border-l-2 flex p-6 flex-col gap-2 max-lg:p-4">
                            <p className="block text-[0.6875rem] leading-[1.0625rem] tracking-[1.98px] uppercase [overflow-wrap:break-word]">
                              Add length for coverage
                            </p>
                            {" "}
                            <p className="block opacity-75 text-color-009 text-sm font-light leading-[1.375rem] [overflow-wrap:break-word]">
                              We suggest adding 1" to the bottom — before adding your mounting height.
                            </p>
                            {" "}
                            <div className="block relative mt-[21.6875px] overflow-hidden bg-accent aspect-[4/3] max-lg:mt-0">
                              <img className="w-full h-60.5 block max-w-full overflow-clip object-cover aspect-[auto_1200/900] max-md:h-[14.4375rem] md:max-lg:h-126" data-component="image" alt="Door-mount shade with added length coverage at the bottom" height="900" src="/assets/cloned/images/fb060a751952.jpg" width="1200" />
                              {" "}
                            </div>
                            {" "}
                          </div>
                          {" "}
                          <div className="border-t border-solid border-color-006 border-r border-b border-l-2 flex p-6 flex-col gap-2 max-lg:p-4">
                            <p className="block text-[0.6875rem] leading-[1.0625rem] tracking-[1.98px] uppercase [overflow-wrap:break-word]">
                              Mounting height guide
                            </p>
                            {" "}
                            <p className="block opacity-75 text-color-009 text-sm font-light leading-[1.375rem] [overflow-wrap:break-word]">
                              <strong className="inline text-accent font-medium">
                                Standard —
                              </strong>
                              {" 3\"–4\" above the glass."}
                              <br className="inline" />
                              {" "}
                              <strong className="inline text-accent font-medium">
                                Hardware clearance —
                              </strong>
                              {" make sure the mount clears any deadbolts, handles, or locks at the top of the door."}
                              <br className="inline" />
                              {" "}
                              <strong className="inline text-accent font-medium">
                                Limited space?
                              </strong>
                              {" Reach out for a custom solution.\n            "}
                            </p>
                            {" "}
                          </div>
                          {" "}
                        </div>
                        {" "}
                      </div>
                      {" "}
                    </div>
                    {" "}
                  </section>
                  <aside className="border-t border-solid border-t-color-006 block -mb-20 pt-12 pb-8 text-accent text-center bg-foreground max-lg:pt-8 max-lg:pb-5" aria-label="Back to top of the Shades Guide">
                    <div className="block max-w-350 px-12 max-md:px-4 md:max-lg:px-[1.92rem]">
                      <a className="h-[42.5938px] inline-flex opacity-70 flex-col items-center gap-2 text-xs font-medium leading-[1.1875rem] tracking-[2.16px] uppercase cursor-pointer" data-component="link" href="#shades-guide-top">
                        <span className="flex justify-center items-center" aria-hidden="true">
                          <svg className="w-auto h-4 block max-w-full overflow-hidden" data-component="icon" fill="none" height="16" viewBox="0 0 14 14" width="16">
                            <path d="M7 11.5V2.5M2.5 7L7 2.5L11.5 7" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" />
                          </svg>
                          {" "}
                        </span>
                        {" "}
                        <span className="block">
                          Back to top
                        </span>
                        {" "}
                      </a>
                      {" "}
                    </div>
                    {" "}
                  </aside>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
            </div>
            {" "}
          </div>
        </section>
        {" "}
      </section>
    </>
  );
}
