import "./ditto.css";
import NavLink from "./components/nav-link";
import Tile from "./components/tile";
import Tile2 from "./components/tile2";
import Tile3 from "./components/tile3";
// Generated by clone-site. Do not edit by hand.
const NavLink_data = [
    { href: "#faq-all-template--20207706210466__faq", label: "All" },
    { href: "#faq-cat-template--20207706210466__faq-general", label: "General" },
    { href: "#faq-cat-template--20207706210466__faq-drapery-hardware", label: "Drapery & Hardware" },
    { href: "#faq-cat-template--20207706210466__faq-roman-shades-woven-woods", label: "Roman Shades & Woven Woods" },
    { href: "#faq-cat-template--20207706210466__faq-trade", label: "Trade" }
];
const Tile_data = [
    { text: "What methods of payment do you accept?", description: "We accept all major credit cards. We also have ShopPay Installments available so you can ", href: "https://everhem.com/collections/all", description2: "shop now", description3: " and pay later." },
    { text: "Does Everhem offer virtual consultations?", description: "Yes we do! Our trained experts will help guide you through design choices and measuring for your Everhem window treatments. Select an available time that works for your schedule ", href: "https://calendly.com/everhem", description2: "here", description3: "." },
    { text: "Does Everhem provide swatches or fabric samples?", description: "Yes! We offer up to 5 swatches for free - just pay shipping! Any swatches beyond the first 5 will be $5 each. Your discount will be automatically applied at checkout - order yours ", href: "/pages/samples", description2: "here", description3: "!" },
    { text: "What's the status of my order?", description: "Once your order has been placed, it enters production at our LA workroom for up to 6 weeks. Items are then packaged and shipped directly to you! Due to various lead times, some items may ship sooner than others. Updated tracking will be provided to you as items are shipped from our workroom. If you'd like more information on the status of your current order(s), please ", href: "mailto:hello@everhem.com", description2: "reach out to us", description3: ". We're happy to help!" },
    { text: "How do I cancel my order?", description: "We are able to cancel your order within 2 business days of when your order was placed; beyond that time, all orders are considered final sale. This is due to the custom nature of our products and how quickly they enter production. Please ", href: "mailto:hello@everhem.com", description2: "contact us", description3: " with your order number to request a cancellation during this timeframe." }
];
const Tile2_data = [
    { description: "Everhem Drapery, Roman Shades, Woven Woods and Hardware are all manufactured by hand in the United States; our products contain intricate components that should be handled with care. If your product arrives damaged or defective, please contact ", description2: " within 48 hours of receiving your order so we can troubleshoot the issue and help with replacement, repair or other resolution. Proof of damage or defect will be required and is subject to review by our team." },
    { description: "If your product arrives incorrect due to customer error, we are not responsible for the product replacement or repair. However, it is always our aim to make things right. Please contact us at ", description2: ", our team is happy to assist you with a prompt resolution." },
    { description: "Additionally, if your product incurs damage due to mishandling, sun or water damage, we are not responsible for the product replacement or repair. However, it is always our aim to make things right. Please contact us at ", description2: ", our team is happy to assist you with a prompt resolution." }
];
const Tile3_data = [
    { text: "What is your Trade discount?", description: "Our Trade discount is 15% year round regardless of order size or volume. Once you have an active trade account, this discount is automatically applied to any order in your cart so long as you're logged in." },
    { text: "Who qualifies to join your Trade program?", description: "Our Trade program is available to design professionals for their respective services and projects. In order to qualify, you must verify your business with the proper credentials during the application process. We do not offer Trade approval for retail or e-commerce businesses who are interested in wholesaling our products." },
    { text: "What credentials do I need to apply?", description: "You will need to upload a valid Business License, EIN or Resale Certificate in order for your application to be approved. We do not require membership in a major design organization (e.g. ASID) but if you belong to one you are encouraged to upload your membership ID. We do not require Design Certification (e.g. NCIDQ) but if you have certification you are encouraged to upload it as well." }
];
const NavLink_meta: string[][] = [
    ["style-link-7"],
    ["n46"],
    ["n47"],
    ["n48"],
    ["n49"]
];
const Tile_meta: string[][] = [
    ["style-link-11", "n96", "n97", "n98", "n99", "n100", "n101"],
    ["style-subscribe", "n103", "n104", "style-div", "n106", "style-shades-guide-shade-type", "n108"],
    ["style-header", "n110", "n111", "n112", "n113", "n114", "n115"],
    ["n116", "n117", "n118", "n119", "n120", "n121", "n122"],
    ["n123", "n124", "n125", "n126", "n127", "n128", "n129"]
];
const Tile2_meta: string[][] = [
    ["n158", "n159"],
    ["n160", "n161"],
    ["n162", "n163"]
];
const Tile3_meta: string[][] = [
    ["n222", "n223", "n224", "n225", "n226", "n227"],
    ["n228", "n229", "n230", "n231", "n232", "n233"],
    ["n234", "n235", "n236", "n237", "n238", "n239"]
];
const NavLink_styles = [
    { className: "border-foreground text-accent bg-foreground" },
    { className: "border-primary" },
    { className: "border-primary" },
    { className: "border-primary" },
    { className: "border-primary" }
];
const Tile2_styles = [
    { className: "mb-3" },
    { className: "mb-3" },
    {  }
];

export default function Page() {
  return (
    <>
      <section className="grid relative grid-cols-[minmax(20px,1fr)_minmax(0,1400px)_minmax(20px,1fr)] grid-rows-1 aspect-[0.397] max-md:grid-cols-[16px_343px_16px] max-md:aspect-[0.106] md:max-lg:grid-cols-[16px_736px_16px] md:max-lg:aspect-[0.258]" data-ditto-id="style-shopify-section-template-20207705292962-main" aria-hidden="true" id="shopify-section-template--20207706210466__faq">
        <section className="block py-16 col-span-full bg-background max-lg:py-10">
          <div className="h-full block max-w-215 mx-auto px-8 max-md:px-4 md:max-lg:px-6">
            <div className="block mb-11 text-center max-lg:mb-7">
              <p className="block mb-3.5 text-color-024 text-xs leading-[1.1875rem] tracking-[0.48px] uppercase [overflow-wrap:break-word]">
                FAQ
              </p>
              <h1 className="block mb-3.5 [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-5xl italic leading-[3.3125rem] [overflow-wrap:break-word] max-lg:text-[2rem] max-lg:leading-[2.1875rem]" data-component="heading">
                How can we help?
              </h1>
              <p className="block max-w-150 mx-auto text-color-011 leading-6 [overflow-wrap:break-word]">
                Search common questions or browse by topic. If you don't find what you need, our team is one message away.
              </p>
            </div>
            <div className="block relative mb-9 max-lg:mb-6">
              <label className="w-px h-px block absolute -m-px overflow-hidden whitespace-nowrap cursor-default" htmlFor="faq-search-template--20207706210466__faq">
                Search FAQs
              </label>
              {" "}
              <input className="w-full h-[3.6875rem] border border-solid border-primary inline-block py-4 pr-4 pl-12 overflow-clip bg-background cursor-text" data-component="input" id="faq-search-template--20207706210466__faq" placeholder="Search FAQs..." type="search" />
              {" "}
              <span className="w-5 h-5 block absolute top-[29.3906px] left-4 text-color-016 transform-[matrix(1,0,0,1,0,-10)] pointer-events-none" aria-hidden="true">
                <svg className="w-auto h-5 block max-w-full overflow-hidden pointer-events-none" data-component="icon" fill="none" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                  <circle cx="9" cy="9" r="6.5" stroke="currentColor" strokeWidth="1.4" />
                  <line x1="13.8" y1="13.8" x2="17.5" y2="17.5" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" />
                </svg>
                {" "}
              </span>
              {" "}
            </div>
            <nav className="border-b border-solid border-b-primary flex mb-11 pb-6 flex-wrap justify-center gap-2 max-lg:mb-7 max-lg:pb-4 max-md:justify-start max-md:overflow-auto max-md:[flex-wrap:initial]" data-ditto-id="style-link-6" data-component="nav" aria-label="FAQ categories">
              {NavLink_data.map((d, i) => <NavLink key={i} d={d} styles={NavLink_styles[i]} />)}
            </nav>
            <div className="block" id="faq-all-template--20207706210466__faq">
              <div className="block mb-12 max-lg:mb-8" id="faq-cat-template--20207706210466__faq-general">
                <h2 className="border-b border-solid border-b-primary block mb-4 pb-2.5 [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-2xl leading-[1.8125rem] [overflow-wrap:break-word] max-lg:text-xl max-lg:leading-6" data-ditto-id="style-button" data-component="heading">
                  General
                </h2>
                <details className="border-b border-solid border-b-primary block" data-ditto-id="style-button-2">
                  <summary className="flex py-4.5 px-1 justify-between items-center gap-4 cursor-pointer">
                    <span className="block grow basis-0">
                      What is the lead time once I place my order?
                    </span>
                    {" "}
                    <span className="w-3.5 h-3.5 block relative shrink-0 before:content-[''] before:block before:absolute before:top-1.5 before:bottom-1.5 before:inset-x-0 before:w-3.5 before:h-px before:bg-clr-1 before:transform-[matrix(1,0,0,1,0,-0.5)] before:origin-[7px_0.5px] 2xl:before:hidden after:content-[''] after:block after:absolute after:inset-y-0 after:right-1.5 after:left-1.5 after:w-px after:h-3.5 after:bg-clr-1 after:transform-[matrix(1,0,0,1,-0.5,0)] after:origin-[0.5px_7px] 2xl:after:hidden" aria-hidden="true" />
                    {" "}
                  </summary>
                  {" "}
                  <div className="block pb-5.5 px-1 text-color-005 leading-[1.625rem]">
                    <p className="block mb-3 [overflow-wrap:break-word]">
                      Once an order is placed, it is sent to enter production right away. Your order is then packed and shipped, time in transit generally being 5 business days. Our current lead times:
                    </p>
                    <p className="block [overflow-wrap:break-word]">
                      <strong className="inline font-bold" data-ditto-id="style-div-2">
                        For Swatches: Items will ship within 3 business days.
                        <br className="inline" />
                        For Drapery, Cafe Curtains, Shades or Hardware: Items are estimated to ship within 6-8 weeks.
                      </strong>
                    </p>
                  </div>
                  {" "}
                </details>
                <details className="border-b border-solid border-b-primary block" data-ditto-id="style-div-3">
                  <summary className="flex py-4.5 px-1 justify-between items-center gap-4 cursor-pointer">
                    <span className="block grow basis-0" data-ditto-id="style-div-4">
                      How and where are Everhem's products made?
                    </span>
                    {" "}
                    <span className="w-3.5 h-3.5 block relative shrink-0 before:content-[''] before:block before:absolute before:top-1.5 before:bottom-1.5 before:inset-x-0 before:w-3.5 before:h-px before:bg-clr-1 before:transform-[matrix(1,0,0,1,0,-0.5)] before:origin-[7px_0.5px] 2xl:before:hidden after:content-[''] after:block after:absolute after:inset-y-0 after:right-1.5 after:left-1.5 after:w-px after:h-3.5 after:bg-clr-1 after:transform-[matrix(1,0,0,1,-0.5,0)] after:origin-[0.5px_7px] 2xl:after:hidden" aria-hidden="true" />
                    {" "}
                  </summary>
                  {" "}
                  <div className="block pb-5.5 px-1 text-color-005 leading-[1.625rem]" data-ditto-id="style-shopify-section-template-20207706308770-tabs">
                    <p className="block [overflow-wrap:break-word]">
                      {"At Everhem, we take immense pride in offering hand-sewn, custom-made window treatments manufactured here in the US. Our raw materials like fabric and shade components such as cords, are part of our global supply chain; however, all manufacturing of our finished product (cutting, sewing, hardware forging & powder coating) are all made in US with trusted partners who are also small businesses. Every piece is meticulously handcrafted, ensuring the highest quality and a level of customization that mass-produced alternatives simply cannot match. We source high quality materials as well as invest in American manufacturing to offer a product of lasting value."}
                    </p>
                  </div>
                  {" "}
                </details>
                <details className="border-b border-solid border-b-primary block" data-ditto-id="style-div-5">
                  <summary className="flex py-4.5 px-1 justify-between items-center gap-4 cursor-pointer">
                    <span className="block grow basis-0" data-ditto-id="style-div-6">
                      Does Everhem have a store or a showroom?
                    </span>
                    {" "}
                    <span className="w-3.5 h-3.5 block relative shrink-0 before:content-[''] before:block before:absolute before:top-1.5 before:bottom-1.5 before:inset-x-0 before:w-3.5 before:h-px before:bg-clr-1 before:transform-[matrix(1,0,0,1,0,-0.5)] before:origin-[7px_0.5px] 2xl:before:hidden after:content-[''] after:block after:absolute after:inset-y-0 after:right-1.5 after:left-1.5 after:w-px after:h-3.5 after:bg-clr-1 after:transform-[matrix(1,0,0,1,-0.5,0)] after:origin-[0.5px_7px] 2xl:after:hidden" aria-hidden="true" />
                    {" "}
                  </summary>
                  {" "}
                  <div className="block pb-5.5 px-1 text-color-005 leading-[1.625rem]">
                    <p className="block mb-3 [overflow-wrap:break-word]">
                      {"Everhem does not have a traditional retail store or dedicated showroom. We are primarily an online custom window treatment company "}
                    </p>
                    <p className="block [overflow-wrap:break-word]">
                      We offer complimentary design services to help guide you through the process from anywhere. You can also order fabric swatches to experience materials and colors in your home before placing an order.
                    </p>
                  </div>
                  {" "}
                </details>
                <details className="border-b border-solid border-b-primary block" data-ditto-id="style-p">
                  <summary className="flex py-4.5 px-1 justify-between items-center gap-4 cursor-pointer">
                    <span className="block grow basis-0" data-ditto-id="style-div-7">
                      What is Everhem's shipping and returns policy?
                    </span>
                    {" "}
                    <span className="w-3.5 h-3.5 block relative shrink-0 before:content-[''] before:block before:absolute before:top-1.5 before:bottom-1.5 before:inset-x-0 before:w-3.5 before:h-px before:bg-clr-1 before:transform-[matrix(1,0,0,1,0,-0.5)] before:origin-[7px_0.5px] 2xl:before:hidden after:content-[''] after:block after:absolute after:inset-y-0 after:right-1.5 after:left-1.5 after:w-px after:h-3.5 after:bg-clr-1 after:transform-[matrix(1,0,0,1,-0.5,0)] after:origin-[0.5px_7px] 2xl:after:hidden" aria-hidden="true" />
                    {" "}
                  </summary>
                  {" "}
                  <div className="block pb-5.5 px-1 text-color-005 leading-[1.625rem]" data-ditto-id="style-div-8">
                    <p className="block [overflow-wrap:break-word]">
                      {"Due to the incredibly nuanced and custom nature of window coverings, all items are considered final sale and we are unable to accept returns. If an item arrives and is incorrect, damaged, or defective, it is our aim to make it right. Please "}
                      <a className="inline text-foreground underline cursor-pointer" data-ditto-id="style-shades-guide-top" data-component="link" href="mailto:hello@everhem.com">
                        contact us
                      </a>
                      {" with any additional questions or issues that may arise."}
                    </p>
                  </div>
                  {" "}
                </details>
                <details className="border-b border-solid border-b-primary block">
                  <summary className="flex py-4.5 px-1 justify-between items-center gap-4 cursor-pointer">
                    <span className="block grow basis-0">
                      Does Everhem have a Trade or Designer program?
                    </span>
                    {" "}
                    <span className="w-3.5 h-3.5 block relative shrink-0 before:content-[''] before:block before:absolute before:top-1.5 before:bottom-1.5 before:inset-x-0 before:w-3.5 before:h-px before:bg-clr-1 before:transform-[matrix(1,0,0,1,0,-0.5)] before:origin-[7px_0.5px] 2xl:before:hidden after:content-[''] after:block after:absolute after:inset-y-0 after:right-1.5 after:left-1.5 after:w-px after:h-3.5 after:bg-clr-1 after:transform-[matrix(1,0,0,1,-0.5,0)] after:origin-[0.5px_7px] 2xl:after:hidden" aria-hidden="true" />
                    {" "}
                  </summary>
                  {" "}
                  <div className="block pb-5.5 px-1 text-color-005 leading-[1.625rem]" data-ditto-id="style-link-8">
                    <p className="block [overflow-wrap:break-word]">
                      {"Yes we do! Find out more and apply "}
                      <a className="inline text-foreground underline cursor-pointer" data-ditto-id="style-link-9" data-component="link" href="/pages/trade">
                        here
                      </a>
                      .
                    </p>
                  </div>
                  {" "}
                </details>
                <details className="border-b border-solid border-b-primary block">
                  <summary className="flex py-4.5 px-1 justify-between items-center gap-4 cursor-pointer">
                    <span className="block grow basis-0">
                      Will I be charged sales tax?
                    </span>
                    {" "}
                    <span className="w-3.5 h-3.5 block relative shrink-0 before:content-[''] before:block before:absolute before:top-1.5 before:bottom-1.5 before:inset-x-0 before:w-3.5 before:h-px before:bg-clr-1 before:transform-[matrix(1,0,0,1,0,-0.5)] before:origin-[7px_0.5px] 2xl:before:hidden after:content-[''] after:block after:absolute after:inset-y-0 after:right-1.5 after:left-1.5 after:w-px after:h-3.5 after:bg-clr-1 after:transform-[matrix(1,0,0,1,-0.5,0)] after:origin-[0.5px_7px] 2xl:after:hidden" aria-hidden="true" />
                    {" "}
                  </summary>
                  {" "}
                  <div className="block pb-5.5 px-1 text-color-005 leading-[1.625rem]" data-ditto-id="style-link-10">
                    <p className="block [overflow-wrap:break-word]">
                      Currently, sales tax will apply for orders shipped to select states. Please note: Sales tax rates vary by state and are subject to change. Be sure to enter your shipping address at checkout to see the sales tax amount.
                    </p>
                  </div>
                  {" "}
                </details>
                {Tile_data.map((d, i) => <Tile key={i} d={d} />)}
                <details className="border-b border-solid border-b-primary block">
                  <summary className="flex py-4.5 px-1 justify-between items-center gap-4 cursor-pointer">
                    <span className="block grow basis-0">
                      What if I need to modify the contents of my order?
                    </span>
                    {" "}
                    <span className="w-3.5 h-3.5 block relative shrink-0 before:content-[''] before:block before:absolute before:top-1.5 before:bottom-1.5 before:inset-x-0 before:w-3.5 before:h-px before:bg-clr-1 before:transform-[matrix(1,0,0,1,0,-0.5)] before:origin-[7px_0.5px] 2xl:before:hidden after:content-[''] after:block after:absolute after:inset-y-0 after:right-1.5 after:left-1.5 after:w-px after:h-3.5 after:bg-clr-1 after:transform-[matrix(1,0,0,1,-0.5,0)] after:origin-[0.5px_7px] 2xl:after:hidden" aria-hidden="true" />
                    {" "}
                  </summary>
                  {" "}
                  <div className="block pb-5.5 px-1 text-color-005 leading-[1.625rem]">
                    <p className="block [overflow-wrap:break-word]">
                      {"We are able to make any changes to your order within 2 business days of when your order was placed. We can update shipping information, cancel items or orders, and change any additional product details. Please "}
                      <a className="inline text-foreground underline cursor-pointer" data-component="link" href="mailto:hello@everhem.com">
                        contact us
                      </a>
                      {" with your order number to make any change requests during this timeframe. Please note: "}
                      <em className="inline italic">
                        We are unable to add items to orders after they have entered into our system.
                      </em>
                    </p>
                  </div>
                  {" "}
                </details>
                <details className="border-b border-solid border-b-primary block">
                  <summary className="flex py-4.5 px-1 justify-between items-center gap-4 cursor-pointer">
                    <span className="block grow basis-0">
                      What if I need to change my shipping address?
                    </span>
                    {" "}
                    <span className="w-3.5 h-3.5 block relative shrink-0 before:content-[''] before:block before:absolute before:top-1.5 before:bottom-1.5 before:inset-x-0 before:w-3.5 before:h-px before:bg-clr-1 before:transform-[matrix(1,0,0,1,0,-0.5)] before:origin-[7px_0.5px] 2xl:before:hidden after:content-[''] after:block after:absolute after:inset-y-0 after:right-1.5 after:left-1.5 after:w-px after:h-3.5 after:bg-clr-1 after:transform-[matrix(1,0,0,1,-0.5,0)] after:origin-[0.5px_7px] 2xl:after:hidden" aria-hidden="true" />
                    {" "}
                  </summary>
                  {" "}
                  <div className="block pb-5.5 px-1 text-color-005 leading-[1.625rem]">
                    <p className="block [overflow-wrap:break-word]">
                      {"We are able to make any changes to your order within 2 business days of when your order was placed. We can update shipping information, cancel items or orders, and change any additional product details. Please "}
                      <a className="inline text-foreground underline cursor-pointer" data-component="link" href="mailto:hello@everhem.com">
                        contact us
                      </a>
                      {" with your order number to make any change requests during this timeframe. Please note: "}
                      <em className="inline italic">
                        We are unable to add items to orders after they have entered into our system.
                      </em>
                    </p>
                  </div>
                  {" "}
                </details>
                <details className="border-b border-solid border-b-primary block">
                  <summary className="flex py-4.5 px-1 justify-between items-center gap-4 cursor-pointer">
                    <span className="block grow basis-0">
                      Why are you called Everhem?
                    </span>
                    {" "}
                    <span className="w-3.5 h-3.5 block relative shrink-0 before:content-[''] before:block before:absolute before:top-1.5 before:bottom-1.5 before:inset-x-0 before:w-3.5 before:h-px before:bg-clr-1 before:transform-[matrix(1,0,0,1,0,-0.5)] before:origin-[7px_0.5px] 2xl:before:hidden after:content-[''] after:block after:absolute after:inset-y-0 after:right-1.5 after:left-1.5 after:w-px after:h-3.5 after:bg-clr-1 after:transform-[matrix(1,0,0,1,-0.5,0)] after:origin-[0.5px_7px] 2xl:after:hidden" aria-hidden="true" />
                    {" "}
                  </summary>
                  {" "}
                  <div className="block pb-5.5 px-1 text-color-005 leading-[1.625rem]">
                    <p className="block [overflow-wrap:break-word]">
                      When husband and wife team Adam and Haley Weidenbaum came up with the idea for Everhem, they were on vacation, visiting Stockholm, Sweden. While there, they learned that "hem" is the Swedish word for home. They liked the double meaning of the Swedish hem and the English hem for hand-sewn products. They thought of the name Everhem to mean window treatments that will last forever in your home.
                    </p>
                  </div>
                  {" "}
                </details>
                <details className="border-b border-solid border-b-primary block">
                  <summary className="flex py-4.5 px-1 justify-between items-center gap-4 cursor-pointer">
                    <span className="block grow basis-0">
                      What is Everhem's product warranty?
                    </span>
                    {" "}
                    <span className="w-3.5 h-3.5 block relative shrink-0 before:content-[''] before:block before:absolute before:top-1.5 before:bottom-1.5 before:inset-x-0 before:w-3.5 before:h-px before:bg-clr-1 before:transform-[matrix(1,0,0,1,0,-0.5)] before:origin-[7px_0.5px] 2xl:before:hidden after:content-[''] after:block after:absolute after:inset-y-0 after:right-1.5 after:left-1.5 after:w-px after:h-3.5 after:bg-clr-1 after:transform-[matrix(1,0,0,1,-0.5,0)] after:origin-[0.5px_7px] 2xl:after:hidden" aria-hidden="true" />
                    {" "}
                  </summary>
                  {" "}
                  <div className="block pb-5.5 px-1 text-color-005 leading-[1.625rem]">
                    <p className="block mb-3 [overflow-wrap:break-word]">
                      Due to the incredibly nuanced and custom nature of window coverings, all items are considered final sale and we are unable to accept returns.
                    </p>
                    {Tile2_data.map((d, i) => <Tile2 key={i} d={d} styles={Tile2_styles[i]} />)}
                  </div>
                  {" "}
                </details>
              </div>
              <div className="block mb-12 max-lg:mb-8" id="faq-cat-template--20207706210466__faq-drapery-hardware">
                <h2 className="border-b border-solid border-b-primary block mb-4 pb-2.5 [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-2xl leading-[1.8125rem] [overflow-wrap:break-word] max-lg:text-xl max-lg:leading-6" data-component="heading">
                  {"Drapery & Hardware"}
                </h2>
                <details className="border-b border-solid border-b-primary block">
                  <summary className="flex py-4.5 px-1 justify-between items-center gap-4 cursor-pointer">
                    <span className="block grow basis-0">
                      What kinds of drapery hardware do you sell?
                    </span>
                    {" "}
                    <span className="w-3.5 h-3.5 block relative shrink-0 before:content-[''] before:block before:absolute before:top-1.5 before:bottom-1.5 before:inset-x-0 before:w-3.5 before:h-px before:bg-clr-1 before:transform-[matrix(1,0,0,1,0,-0.5)] before:origin-[7px_0.5px] 2xl:before:hidden after:content-[''] after:block after:absolute after:inset-y-0 after:right-1.5 after:left-1.5 after:w-px after:h-3.5 after:bg-clr-1 after:transform-[matrix(1,0,0,1,-0.5,0)] after:origin-[0.5px_7px] 2xl:after:hidden" aria-hidden="true" />
                    {" "}
                  </summary>
                  {" "}
                  <div className="block pb-5.5 px-1 text-color-005 leading-[1.625rem]">
                    <p className="block [overflow-wrap:break-word]">
                      All of our drapery is designed to work solely with rod and ring hardware. We offer three different styles of drapery hardware: Curved Return, Right Angle Return and Ball Finial. These styles are available in three different finishes: Matte Black, Satin Brass and Oil Rubbed Bronze.
                    </p>
                  </div>
                  {" "}
                </details>
                <details className="border-b border-solid border-b-primary block">
                  <summary className="flex py-4.5 px-1 justify-between items-center gap-4 cursor-pointer">
                    <span className="block grow basis-0">
                      What's the ideal length and width of a drapery panel?
                    </span>
                    {" "}
                    <span className="w-3.5 h-3.5 block relative shrink-0 before:content-[''] before:block before:absolute before:top-1.5 before:bottom-1.5 before:inset-x-0 before:w-3.5 before:h-px before:bg-clr-1 before:transform-[matrix(1,0,0,1,0,-0.5)] before:origin-[7px_0.5px] 2xl:before:hidden after:content-[''] after:block after:absolute after:inset-y-0 after:right-1.5 after:left-1.5 after:w-px after:h-3.5 after:bg-clr-1 after:transform-[matrix(1,0,0,1,-0.5,0)] after:origin-[0.5px_7px] 2xl:after:hidden" aria-hidden="true" />
                    {" "}
                  </summary>
                  {" "}
                  <div className="block pb-5.5 px-1 text-color-005 leading-[1.625rem]">
                    <p className="block [overflow-wrap:break-word]">
                      {"Ideal is determined by your window and space! We have design guidelines through the customization process so you have our design advice every step of the way. Still have questions? "}
                      <a className="inline text-foreground underline cursor-pointer" data-component="link" href="mailto:hello@everhem.com">
                        Reach out
                      </a>
                      {" to us or "}
                      <a className="inline text-foreground underline cursor-pointer" data-component="link" href="https://calendly.com/everhem">
                        schedule a virtual consultation
                      </a>
                      {" with one of our trained experts. We're happy to help!"}
                    </p>
                  </div>
                  {" "}
                </details>
                <details className="border-b border-solid border-b-primary block">
                  <summary className="flex py-4.5 px-1 justify-between items-center gap-4 cursor-pointer">
                    <span className="block grow basis-0">
                      What style drapery do you sell and which should I choose?
                    </span>
                    {" "}
                    <span className="w-3.5 h-3.5 block relative shrink-0 before:content-[''] before:block before:absolute before:top-1.5 before:bottom-1.5 before:inset-x-0 before:w-3.5 before:h-px before:bg-clr-1 before:transform-[matrix(1,0,0,1,0,-0.5)] before:origin-[7px_0.5px] 2xl:before:hidden after:content-[''] after:block after:absolute after:inset-y-0 after:right-1.5 after:left-1.5 after:w-px after:h-3.5 after:bg-clr-1 after:transform-[matrix(1,0,0,1,-0.5,0)] after:origin-[0.5px_7px] 2xl:after:hidden" aria-hidden="true" />
                    {" "}
                  </summary>
                  {" "}
                  <div className="block pb-5.5 px-1 text-color-005 leading-[1.625rem]">
                    <p className="block [overflow-wrap:break-word]">
                      We offer our drapery in 3 different pleat styles: Box, Tailored and Pinch. Box pleat drapery is sewn in such a way that the actual pleats are on the back side of the drapery creating a structured, columnar look to the fabric in the front. This is the sleekest, most modern looking style we offer. Tailored pleat drapery is pinched at the very top, and each individual pleat gradually widen from top to bottom. This is somewhat of a transitional pleat style between contemporary and traditional. Pinch pleats are pinched about 3 inches down from the top of the drape, creating a sideways bow tie look at the top before gradually widening out. This is the most traditional looking drape we offer. For a casual, modern look, we recommend Box Pleat. For a versatile, transitional space, we recommend Tailored Pleat. For a space with traditional design in mind, we recommend Pinch Pleat.
                    </p>
                  </div>
                  {" "}
                </details>
                <details className="border-b border-solid border-b-primary block">
                  <summary className="flex py-4.5 px-1 justify-between items-center gap-4 cursor-pointer">
                    <span className="block grow basis-0">
                      Why do I need custom drapery as opposed to standard sized panels?
                    </span>
                    {" "}
                    <span className="w-3.5 h-3.5 block relative shrink-0 before:content-[''] before:block before:absolute before:top-1.5 before:bottom-1.5 before:inset-x-0 before:w-3.5 before:h-px before:bg-clr-1 before:transform-[matrix(1,0,0,1,0,-0.5)] before:origin-[7px_0.5px] 2xl:before:hidden after:content-[''] after:block after:absolute after:inset-y-0 after:right-1.5 after:left-1.5 after:w-px after:h-3.5 after:bg-clr-1 after:transform-[matrix(1,0,0,1,-0.5,0)] after:origin-[0.5px_7px] 2xl:after:hidden" aria-hidden="true" />
                    {" "}
                  </summary>
                  {" "}
                  <div className="block pb-5.5 px-1 text-color-005 leading-[1.625rem]">
                    <p className="block [overflow-wrap:break-word]">
                      While everyone's home, windows and design needs are different, standard sized drapery panels only come in two widths (50" and 100") and four lengths (84", 96", 108" and 120"). For many windows these dimensions will result in drapery panels that look flat when drawn closed, aren't long enough to kiss the floor or are too long and get dragged all over the floor when the drapes are opened and closed. In addition, the styles available for standard sized panels very often will not match the aesthetic of the customer. Everhem custom drapery is made for the specific width and length of your window, taking into account your mounting height, proper fullness requirements and the fact that various fabrics grow in length over time. Our company was founded by an interior designer who knows just how vital quality window coverings are to the overall design of a space, and our fabric choices have been carefully curated to ensure that everything we design using your custom measurements will look bespoke, beautiful and stand the test of time in your space.
                    </p>
                  </div>
                  {" "}
                </details>
                <details className="border-b border-solid border-b-primary block">
                  <summary className="flex py-4.5 px-1 justify-between items-center gap-4 cursor-pointer">
                    <span className="block grow basis-0">
                      How many rings will I need?
                    </span>
                    {" "}
                    <span className="w-3.5 h-3.5 block relative shrink-0 before:content-[''] before:block before:absolute before:top-1.5 before:bottom-1.5 before:inset-x-0 before:w-3.5 before:h-px before:bg-clr-1 before:transform-[matrix(1,0,0,1,0,-0.5)] before:origin-[7px_0.5px] 2xl:before:hidden after:content-[''] after:block after:absolute after:inset-y-0 after:right-1.5 after:left-1.5 after:w-px after:h-3.5 after:bg-clr-1 after:transform-[matrix(1,0,0,1,-0.5,0)] after:origin-[0.5px_7px] 2xl:after:hidden" aria-hidden="true" />
                    {" "}
                  </summary>
                  {" "}
                  <div className="block pb-5.5 px-1 text-color-005 leading-[1.625rem]">
                    <p className="block [overflow-wrap:break-word]">
                      {"For Drapery & Hardware ordered together, we will provide the correct amount of rings required to properly install your drapery. If you need to calculate the rings required for another configuration, please "}
                      <a className="inline text-foreground underline cursor-pointer" data-component="link" href="mailto:hello@everhem.com">
                        contact us
                      </a>
                      , we're happy to help!
                    </p>
                  </div>
                  {" "}
                </details>
                <details className="border-b border-solid border-b-primary block">
                  <summary className="flex py-4.5 px-1 justify-between items-center gap-4 cursor-pointer">
                    <span className="block grow basis-0">
                      What linings do you offer for your drapery?
                    </span>
                    {" "}
                    <span className="w-3.5 h-3.5 block relative shrink-0 before:content-[''] before:block before:absolute before:top-1.5 before:bottom-1.5 before:inset-x-0 before:w-3.5 before:h-px before:bg-clr-1 before:transform-[matrix(1,0,0,1,0,-0.5)] before:origin-[7px_0.5px] 2xl:before:hidden after:content-[''] after:block after:absolute after:inset-y-0 after:right-1.5 after:left-1.5 after:w-px after:h-3.5 after:bg-clr-1 after:transform-[matrix(1,0,0,1,-0.5,0)] after:origin-[0.5px_7px] 2xl:after:hidden" aria-hidden="true" />
                    {" "}
                  </summary>
                  {" "}
                  <div className="block pb-5.5 px-1 text-color-005 leading-[1.625rem]">
                    <p className="block mb-3 [overflow-wrap:break-word]">
                      We offer three different lining options: Unlined, Privacy and Blackout. Unlined will be the material itself and nothing added, this provides limited light diffusion but still gives some privacy. Privacy Lining is a white lining; it allows natural, diffused light to pass through and gives a room a warm glow. Blackout Lining is a white lining: it allows no light to pass through and creates virtual darkness any time of day. Consider layering blackout lined shades and drapery in spaces that need total darkness.
                    </p>
                    <p className="block [overflow-wrap:break-word]">
                      Please Note: Unlined Drapery will be at higher risk for sun damage over time. We recommend Privacy or Blackout for windows that receive harsh sunlight on a consistent basis.
                    </p>
                  </div>
                  {" "}
                </details>
              </div>
              <div className="block mb-12 max-lg:mb-8" id="faq-cat-template--20207706210466__faq-roman-shades-woven-woods">
                <h2 className="border-b border-solid border-b-primary block mb-4 pb-2.5 [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-2xl leading-[1.8125rem] [overflow-wrap:break-word] max-lg:text-xl max-lg:leading-6" data-component="heading">
                  {"Roman Shades & Woven Woods"}
                </h2>
                <details className="border-b border-solid border-b-primary block">
                  <summary className="flex py-4.5 px-1 justify-between items-center gap-4 cursor-pointer">
                    <span className="block grow basis-0">
                      What's the difference between Inside and Outside Mount shades?
                    </span>
                    {" "}
                    <span className="w-3.5 h-3.5 block relative shrink-0 before:content-[''] before:block before:absolute before:top-1.5 before:bottom-1.5 before:inset-x-0 before:w-3.5 before:h-px before:bg-clr-1 before:transform-[matrix(1,0,0,1,0,-0.5)] before:origin-[7px_0.5px] 2xl:before:hidden after:content-[''] after:block after:absolute after:inset-y-0 after:right-1.5 after:left-1.5 after:w-px after:h-3.5 after:bg-clr-1 after:transform-[matrix(1,0,0,1,-0.5,0)] after:origin-[0.5px_7px] 2xl:after:hidden" aria-hidden="true" />
                    {" "}
                  </summary>
                  {" "}
                  <div className="block pb-5.5 px-1 text-color-005 leading-[1.625rem]">
                    <p className="block [overflow-wrap:break-word]">
                      Inside Mount shades get mounted or positioned inside the window frame or casement. In order to do this, there must be the required mounting depth inside the window for the shade to lay flush with the window's opening (depth required varies by Custom Control selection). Inside mount shades are great for a seamless, modern look. Since the shade sits inside the window, if total blackout is required, inside mount shades may not be the best way to go. Outside mount shades get mounted outside the window on the window frame itself, the drywall above the window or the door frame above the glass. Outside mount shades are recommended for rooms where blackout is of utmost importance. Outside mount shades are also recommended for windows without sufficient mounting depth and for all door mounted shades.
                    </p>
                  </div>
                  {" "}
                </details>
                <details className="border-b border-solid border-b-primary block">
                  <summary className="flex py-4.5 px-1 justify-between items-center gap-4 cursor-pointer">
                    <span className="block grow basis-0">
                      What's the difference between the Pleated and Flat Roman Shade styles?
                    </span>
                    {" "}
                    <span className="w-3.5 h-3.5 block relative shrink-0 before:content-[''] before:block before:absolute before:top-1.5 before:bottom-1.5 before:inset-x-0 before:w-3.5 before:h-px before:bg-clr-1 before:transform-[matrix(1,0,0,1,0,-0.5)] before:origin-[7px_0.5px] 2xl:before:hidden after:content-[''] after:block after:absolute after:inset-y-0 after:right-1.5 after:left-1.5 after:w-px after:h-3.5 after:bg-clr-1 after:transform-[matrix(1,0,0,1,-0.5,0)] after:origin-[0.5px_7px] 2xl:after:hidden" aria-hidden="true" />
                    {" "}
                  </summary>
                  {" "}
                  <div className="block pb-5.5 px-1 text-color-005 leading-[1.625rem]">
                    <p className="block [overflow-wrap:break-word]">
                      Pleated Roman shades have structured pleats sewn into the fabric of the shade. Flat shades are square across the bottom but have no structured pleats so they are a little more casual in look.
                    </p>
                  </div>
                  {" "}
                </details>
              </div>
              <div className="block mb-12 max-lg:mb-8" id="faq-cat-template--20207706210466__faq-trade">
                <h2 className="border-b border-solid border-b-primary block mb-4 pb-2.5 [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-2xl leading-[1.8125rem] [overflow-wrap:break-word] max-lg:text-xl max-lg:leading-6" data-component="heading">
                  Trade
                </h2>
                {Tile3_data.map((d, i) => <Tile3 key={i} d={d} />)}
                <details className="border-b border-solid border-b-primary block">
                  <summary className="flex py-4.5 px-1 justify-between items-center gap-4 cursor-pointer">
                    <span className="block grow basis-0">
                      How do I apply for a Trade account?
                    </span>
                    {" "}
                    <span className="w-3.5 h-3.5 block relative shrink-0 before:content-[''] before:block before:absolute before:top-1.5 before:bottom-1.5 before:inset-x-0 before:w-3.5 before:h-px before:bg-clr-1 before:transform-[matrix(1,0,0,1,0,-0.5)] before:origin-[7px_0.5px] 2xl:before:hidden after:content-[''] after:block after:absolute after:inset-y-0 after:right-1.5 after:left-1.5 after:w-px after:h-3.5 after:bg-clr-1 after:transform-[matrix(1,0,0,1,-0.5,0)] after:origin-[0.5px_7px] 2xl:after:hidden" aria-hidden="true" />
                    {" "}
                  </summary>
                  {" "}
                  <div className="block pb-5.5 px-1 text-color-005 leading-[1.625rem]">
                    <p className="block [overflow-wrap:break-word]">
                      {"Click "}
                      <a className="inline text-foreground underline cursor-pointer" data-component="link" href="/pages/trade">
                        here
                      </a>
                      {" to complete our trade application. You will receive notification of your membership status within one business day."}
                    </p>
                  </div>
                  {" "}
                </details>
                <details className="border-b border-solid border-b-primary block">
                  <summary className="flex py-4.5 px-1 justify-between items-center gap-4 cursor-pointer">
                    <span className="block grow basis-0">
                      Does your Trade program offer tax exemption?
                    </span>
                    {" "}
                    <span className="w-3.5 h-3.5 block relative shrink-0 before:content-[''] before:block before:absolute before:top-1.5 before:bottom-1.5 before:inset-x-0 before:w-3.5 before:h-px before:bg-clr-1 before:transform-[matrix(1,0,0,1,0,-0.5)] before:origin-[7px_0.5px] 2xl:before:hidden after:content-[''] after:block after:absolute after:inset-y-0 after:right-1.5 after:left-1.5 after:w-px after:h-3.5 after:bg-clr-1 after:transform-[matrix(1,0,0,1,-0.5,0)] after:origin-[0.5px_7px] 2xl:after:hidden" aria-hidden="true" />
                    {" "}
                  </summary>
                  {" "}
                  <div className="block pb-5.5 px-1 text-color-005 leading-[1.625rem]">
                    <p className="block mb-3 [overflow-wrap:break-word]">
                      Sales tax is applied in select states. If you hold a valid resale license, you can be set up as tax-exempt.
                    </p>
                    <p className="block [overflow-wrap:break-word]">
                      {"As a trade member, you can upload your resale license directly within the Trade application to ensure your account is set up correctly from the start. If you're an existing trade member, you can email your resale license to "}
                      <a className="inline text-foreground underline cursor-pointer" data-component="link" href="mailto:trade@everhem.com">
                        trade@everhem.com
                      </a>
                      {" and our team will update your account to reflect tax-exempt status."}
                    </p>
                  </div>
                  {" "}
                </details>
                <details className="border-b border-solid border-b-primary block">
                  <summary className="flex py-4.5 px-1 justify-between items-center gap-4 cursor-pointer">
                    <span className="block grow basis-0">
                      How do I log into my Trade account?
                    </span>
                    {" "}
                    <span className="w-3.5 h-3.5 block relative shrink-0 before:content-[''] before:block before:absolute before:top-1.5 before:bottom-1.5 before:inset-x-0 before:w-3.5 before:h-px before:bg-clr-1 before:transform-[matrix(1,0,0,1,0,-0.5)] before:origin-[7px_0.5px] 2xl:before:hidden after:content-[''] after:block after:absolute after:inset-y-0 after:right-1.5 after:left-1.5 after:w-px after:h-3.5 after:bg-clr-1 after:transform-[matrix(1,0,0,1,-0.5,0)] after:origin-[0.5px_7px] 2xl:after:hidden" aria-hidden="true" />
                    {" "}
                  </summary>
                  {" "}
                  <div className="block pb-5.5 px-1 text-color-005 leading-[1.625rem]">
                    <p className="block [overflow-wrap:break-word]">
                      {"Once your account has been set up, you can log in by "}
                      <a className="inline text-foreground underline cursor-pointer" data-component="link" href="https://everhem.com/account/login">
                        clicking here
                      </a>
                      .
                    </p>
                  </div>
                  {" "}
                </details>
                <details className="border-b border-solid border-b-primary block">
                  <summary className="flex py-4.5 px-1 justify-between items-center gap-4 cursor-pointer">
                    <span className="block grow basis-0">
                      How do I place a Trade order?
                    </span>
                    {" "}
                    <span className="w-3.5 h-3.5 block relative shrink-0 before:content-[''] before:block before:absolute before:top-1.5 before:bottom-1.5 before:inset-x-0 before:w-3.5 before:h-px before:bg-clr-1 before:transform-[matrix(1,0,0,1,0,-0.5)] before:origin-[7px_0.5px] 2xl:before:hidden after:content-[''] after:block after:absolute after:inset-y-0 after:right-1.5 after:left-1.5 after:w-px after:h-3.5 after:bg-clr-1 after:transform-[matrix(1,0,0,1,-0.5,0)] after:origin-[0.5px_7px] 2xl:after:hidden" aria-hidden="true" />
                    {" "}
                  </summary>
                  {" "}
                  <div className="block pb-5.5 px-1 text-color-005 leading-[1.625rem]">
                    <p className="block mb-3 [overflow-wrap:break-word]">
                      Once your Trade account has been activated, you can simply sign in to shop and place orders on our website. Your 15% Trade discount will be automatically applied to all orders at checkout.
                    </p>
                    <p className="block [overflow-wrap:break-word]">
                      {"Additionally, some Trade orders qualify for additional customizations, and will be processed by the Everhem Trade Team. Please reach out to our "}
                      <a className="inline text-foreground underline cursor-pointer" data-component="link" href="mailto:trade@everhem.com">
                        Designer Liaison
                      </a>
                      {" to find out more."}
                    </p>
                  </div>
                  {" "}
                </details>
                <details className="border-b border-solid border-b-primary block">
                  <summary className="flex py-4.5 px-1 justify-between items-center gap-4 cursor-pointer">
                    <span className="block grow basis-0">
                      Do you offer fabric swatches?
                    </span>
                    {" "}
                    <span className="w-3.5 h-3.5 block relative shrink-0 before:content-[''] before:block before:absolute before:top-1.5 before:bottom-1.5 before:inset-x-0 before:w-3.5 before:h-px before:bg-clr-1 before:transform-[matrix(1,0,0,1,0,-0.5)] before:origin-[7px_0.5px] 2xl:before:hidden after:content-[''] after:block after:absolute after:inset-y-0 after:right-1.5 after:left-1.5 after:w-px after:h-3.5 after:bg-clr-1 after:transform-[matrix(1,0,0,1,-0.5,0)] after:origin-[0.5px_7px] 2xl:after:hidden" aria-hidden="true" />
                    {" "}
                  </summary>
                  {" "}
                  <div className="block pb-5.5 px-1 text-color-005 leading-[1.625rem]">
                    <p className="block [overflow-wrap:break-word]">
                      {"Yes! You can order swatches online or "}
                      <a className="inline text-foreground underline cursor-pointer" data-component="link" href="mailto:trade@everhem.com">
                        contact us
                      </a>
                      {" anytime to request any swatch(es) you may need."}
                    </p>
                  </div>
                  {" "}
                </details>
                <details className="border-b border-solid border-b-primary block">
                  <summary className="flex py-4.5 px-1 justify-between items-center gap-4 cursor-pointer">
                    <span className="block grow basis-0">
                      Do you work with COM?
                    </span>
                    {" "}
                    <span className="w-3.5 h-3.5 block relative shrink-0 before:content-[''] before:block before:absolute before:top-1.5 before:bottom-1.5 before:inset-x-0 before:w-3.5 before:h-px before:bg-clr-1 before:transform-[matrix(1,0,0,1,0,-0.5)] before:origin-[7px_0.5px] 2xl:before:hidden after:content-[''] after:block after:absolute after:inset-y-0 after:right-1.5 after:left-1.5 after:w-px after:h-3.5 after:bg-clr-1 after:transform-[matrix(1,0,0,1,-0.5,0)] after:origin-[0.5px_7px] 2xl:after:hidden" aria-hidden="true" />
                    {" "}
                  </summary>
                  {" "}
                  <div className="block pb-5.5 px-1 text-color-005 leading-[1.625rem]">
                    <p className="block mb-3 [overflow-wrap:break-word]">
                      {"We will absolutely work with COM. Please contact your dedicated "}
                      <a className="inline text-foreground underline cursor-pointer" data-component="link" href="mailto:trade@everhem.com">
                        Trade Specialist
                      </a>
                      {" to give you next steps!"}
                    </p>
                    <p className="block [overflow-wrap:break-word]">
                      <strong className="inline font-bold">
                        Please Note:
                      </strong>
                      {" We do not order COM ourselves. We will work with you on yardage calculations but you will be responsible for ordering the material and shipping it to us. We are not responsible for any fabric that arrives damaged or flawed. And, most importantly, we are not responsible for COM fabrics which may grow. We have tested our own fabrics and we understand how they react over time and we factor that in with our measurement guidelines. But we cannot know how COM will react over time and therefore we cannot guarantee or warranty it against expansion."}
                    </p>
                  </div>
                  {" "}
                </details>
                <details className="border-b border-solid border-b-primary block">
                  <summary className="flex py-4.5 px-1 justify-between items-center gap-4 cursor-pointer">
                    <span className="block grow basis-0">
                      What other kinds of window treatments can you make that aren't available on your site?
                    </span>
                    {" "}
                    <span className="w-3.5 h-3.5 block relative shrink-0 before:content-[''] before:block before:absolute before:top-1.5 before:bottom-1.5 before:inset-x-0 before:w-3.5 before:h-px before:bg-clr-1 before:transform-[matrix(1,0,0,1,0,-0.5)] before:origin-[7px_0.5px] 2xl:before:hidden after:content-[''] after:block after:absolute after:inset-y-0 after:right-1.5 after:left-1.5 after:w-px after:h-3.5 after:bg-clr-1 after:transform-[matrix(1,0,0,1,-0.5,0)] after:origin-[0.5px_7px] 2xl:after:hidden" aria-hidden="true" />
                    {" "}
                  </summary>
                  {" "}
                  <div className="block pb-5.5 px-1 text-color-005 leading-[1.625rem]">
                    <p className="block [overflow-wrap:break-word]">
                      {"We can accommodate additional customized requests for members in our Trade Program. Some of these custom options include Relaxed Shades, additional Hardware finishes and styles, and COM capabilities. Please reach out to "}
                      <a className="inline text-foreground underline cursor-pointer" data-component="link" href="mailto:trade@everhem.com">
                        trade@everhem.com
                      </a>
                      {" and we will be happy to help assist on a custom order request."}
                    </p>
                  </div>
                  {" "}
                </details>
              </div>
              {" "}
            </div>
            <div className="block mt-16 py-12 px-[2.4rem] text-center bg-accent max-lg:mt-10 max-lg:py-8 max-lg:px-6">
              <h3 className="block mb-2.5 [font-family:'Freight_Big_Pro',_'Playfair_Display',_'Times_New_Roman',_Georgia,_serif] text-[1.75rem] italic leading-[2.125rem] [overflow-wrap:break-word] max-lg:text-xl max-lg:leading-6" data-component="heading">
                Still have questions?
              </h3>
              <p className="block mb-5 text-color-003 [overflow-wrap:break-word]">
                Our team is here to help with anything we missed.
              </p>
              <a className="border border-solid border-foreground inline-block py-3.5 px-7 text-accent text-sm leading-[1.375rem] tracking-[0.56px] uppercase bg-foreground cursor-pointer" data-component="button" href="/pages/contact">
                Contact us
              </a>
            </div>
          </div>
          {" "}
        </section>
        {"  "}
      </section>
    </>
  );
}
